"""
Emit artifacts from a PartIR:
  - parametric CadQuery source (.py)
  - PARAMS sidecar (.params.json)
  - provenance metadata (.meta.json)

Nothing here imports cadquery — emit is pure string manipulation.
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path

from . import __version__
from .describe import describe_dimensions
from .ir import PartIR

_HEADER = """\
import cadquery as cq
{extra_imports}
# Generated by CadQuarry v{version} — seed {seed} — CC0-1.0
# https://github.com/jacobjennings/CadQuarry
"""

_PARAMS_BLOCK = """\
PARAMS = {{
{entries}
}}
"""

_BUILD_OPEN = """\

def build(p):
"""

_BUILD_CLOSE = """\
    return result
"""

_CANONICAL = """\

result = build({k: v["default"] for k, v in PARAMS.items()})
"""


def _format_param_entry(name: str, spec: dict) -> str:
    """Format one PARAMS entry as an indented dict literal."""
    pairs: list[str] = []
    for k, v in spec.items():
        if isinstance(v, str):
            pairs.append(f'"{k}": {v!r}')
        elif isinstance(v, bool):
            pairs.append(f'"{k}": {"True" if v else "False"}')
        elif isinstance(v, list):
            pairs.append(f'"{k}": {v!r}')
        else:
            pairs.append(f'"{k}": {v!r}')
    inner = ", ".join(pairs)
    return f'    "{name}": {{{inner}}},'


def _collect_extra_imports(part: PartIR) -> list[str]:
    """
    Aggregate any extra top-level import lines an operation needs (beyond the
    always-present ``import cadquery as cq``), de-duplicated and sorted so the
    emitted source is byte-stable for a given IR.

    An operation opts in by defining ``required_imports(self) -> list[str]``;
    most ops have no extra imports and are skipped.  This is how the gear /
    threaded families pull in their build123d-stack libraries.
    """
    seen: set[str] = set()
    for op in part.operations:
        getter = getattr(op, "required_imports", None)
        if getter is None:
            continue
        for line in getter():
            seen.add(line)
    return sorted(seen)


def emit_source(part: PartIR) -> str:
    """Return the full .py source for a generated part."""
    version = __version__
    seed = part.metadata.seed

    # Header — `import cadquery as cq` plus any per-part extra imports.
    extra = _collect_extra_imports(part)
    extra_block = ("\n".join(extra) + "\n") if extra else ""
    lines: list[str] = [
        _HEADER.format(version=version, seed=seed, extra_imports=extra_block)
    ]

    # PARAMS block
    schema = part.params_schema()
    entries = "\n".join(_format_param_entry(k, v) for k, v in schema.items())
    lines.append(_PARAMS_BLOCK.format(entries=entries))

    # build(p) function
    lines.append(_BUILD_OPEN)
    for op in part.operations:
        for line in op.to_code():
            lines.append(line)
    lines.append(_BUILD_CLOSE)

    # Canonical instance
    lines.append(_CANONICAL)

    return "\n".join(lines)


def emit_params_json(part: PartIR) -> dict:
    """Return the .params.json sidecar as a Python dict."""
    return {
        "cadquarry_version": __version__,
        "part_id": part.id,
        "params": part.params_schema(),
    }


def _part_descriptor(part: PartIR) -> dict | None:
    """
    Build a structured, family-specific design descriptor for the metadata,
    resolved against the part's default parameters.  An operation opts in by
    defining ``describe(params) -> dict`` (currently the gear / threaded base
    ops); this captures categorical design intent — gear kind, thread standard,
    pitch, module, designation — that otherwise lives only in the emitted
    source.  Returns ``None`` for families with no describable op.
    """
    defaults = part.default_params()
    descriptor: dict = {}
    for op in part.operations:
        describe = getattr(op, "describe", None)
        if describe is None:
            continue
        descriptor.update(describe(defaults))
    return descriptor or None


def emit_meta_json(part: PartIR, geometry_signature: dict | None = None) -> dict:
    """Return the .meta.json provenance record as a Python dict."""
    meta = {
        "cadquarry_version": __version__,
        "part_id": part.id,
        "seed": part.metadata.seed,
        "generator_version": part.metadata.generator_version,
        "family": part.metadata.family,
        "tier": part.metadata.tier,
        "symmetry": part.metadata.symmetry,
        "op_count": part.metadata.op_count,
        "ir_hash": part.ir_hash(),
        "license": "CC0-1.0",
    }
    descriptor = _part_descriptor(part)
    if descriptor is not None:
        meta["descriptor"] = descriptor
    # Procedural, prompt-friendly dimension summary (no AI; pure IR walk).
    meta["dimensions"] = describe_dimensions(part)
    if geometry_signature:
        meta["geometry_signature"] = geometry_signature
    return meta


def write_part(
    part: PartIR,
    out_dir: Path,
    geometry_signature: dict | None = None,
) -> dict[str, Path]:
    """
    Write all artifacts for a part to out_dir.
    Returns a dict of artifact type → path.
    """
    parts_dir = out_dir / "parts"
    params_dir = out_dir / "params"
    meta_dir = out_dir / "meta"
    dims_dir = out_dir / "dims"
    for d in (parts_dir, params_dir, meta_dir, dims_dir):
        d.mkdir(parents=True, exist_ok=True)

    pid = part.id
    py_path = parts_dir / f"{pid}.py"
    params_path = params_dir / f"{pid}.params.json"
    meta_path = meta_dir / f"{pid}.meta.json"
    dims_path = dims_dir / f"{pid}.txt"

    meta = emit_meta_json(part, geometry_signature)

    py_path.write_text(emit_source(part), encoding="utf-8")
    params_path.write_text(
        json.dumps(emit_params_json(part), indent=2), encoding="utf-8"
    )
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")
    dims_path.write_text(meta["dimensions"]["text"] + "\n", encoding="utf-8")

    return {"py": py_path, "params": params_path, "meta": meta_path, "dims": dims_path}
