import cadquery as cq

# Generated by CadQuarry v0.1.0 — seed 1234004287 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 48.06, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 26.3, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 51.7, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "hole_d": {"type": 'float', "default": 5.3, "min": 2.0, "max": 5.9, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "pocket_w": {"type": 'float', "default": 20.7, "min": 10.3, "max": 38.4, "step": 1.0, "group": 'Pocket', "label": 'Pocket width (mm)'},
    "pocket_d": {"type": 'float', "default": 14.0, "min": 7.0, "max": 21.0, "step": 1.0, "group": 'Pocket', "label": 'Pocket depth (mm)'},
    "pocket_h": {"type": 'float', "default": 19.8, "min": 7.9, "max": 43.9, "step": 0.5, "group": 'Pocket', "label": 'Pocket height (mm)'},
    "filleted2": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["pocket_w"], p["pocket_d"])
        .cutBlind(-p["pocket_h"])
    )
    if p["filleted2"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.058108432721954796)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
