import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234004591 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 77.49, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 44.7, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 100.0, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "hole_d": {"type": 'float', "default": 6.4, "min": 2.0, "max": 13.1, "step": 0.5, "group": 'Holes', "label": 'Square hole size (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "filleted2": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "side_tube_d": {"type": 'float', "default": 11.4, "min": 4.6, "max": 22.4, "step": 1.0, "group": 'Side Tube', "label": 'Side tube diameter (mm)'},
    "side_tube_len": {"type": 'float', "default": 10.8, "min": 3.2, "max": 34.2, "step": 1.0, "group": 'Side Tube', "label": 'Side tube length (mm)'},
    "side_bore_d": {"type": 'float', "default": 4.9, "min": 2.0, "max": 8.6, "step": 0.5, "group": 'Side Tube', "label": 'Side bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().rect(p["hole_d"], p["hole_d"]).cutThruAll()
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.08094736689099608)
    if p["filleted2"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.07852218370563628)
    result = (
        result.faces('>X').workplane()
        .circle(p["side_tube_d"] / 2).extrude(p["side_tube_len"])
    )
    result = (
        result.faces('>X').workplane()
        .hole(p["side_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
