import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004211 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 65.94, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 27.3, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 38.9, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "bolt_d": {"type": 'float', "default": 5.3, "min": 3.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Bolt hole diameter (mm)'},
    "bolt_r": {"type": 'float', "default": 19.8, "min": 13.2, "max": 29.7, "step": 1.0, "group": 'Holes', "label": 'Bolt circle radius (mm)'},
    "n_bolts": {"type": 'int', "default": 6, "min": 3, "max": 12, "step": 1, "group": 'Holes', "label": 'Number of bolts'},
    "boss_d": {"type": 'float', "default": 17.9, "min": 8.9, "max": 35.8, "step": 1.0, "group": 'Boss', "label": 'Boss diameter (mm)'},
    "boss_h": {"type": 'float', "default": 7.2, "min": 2.9, "max": 18.0, "step": 1.0, "group": 'Boss', "label": 'Boss height (mm)'},
    "boss_bore_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 12.5, "step": 0.1, "group": 'Boss', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .polarArray(p["bolt_r"], 0, 360, p["n_bolts"])
        .hole(p["bolt_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .circle(p["boss_d"] / 2).extrude(p["boss_h"])
    )
    result = (
        result.faces('>Z').workplane()
        .hole(p["boss_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
