import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234004051 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 45, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 23.1, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 75.0, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "hole_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 5.2, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "pocket_w": {"type": 'float', "default": 23.8, "min": 11.9, "max": 36.0, "step": 1.0, "group": 'Pocket', "label": 'Pocket width (mm)'},
    "pocket_d": {"type": 'float', "default": 9.5, "min": 4.8, "max": 18.5, "step": 1.0, "group": 'Pocket', "label": 'Pocket depth (mm)'},
    "pocket_h": {"type": 'float', "default": 23.9, "min": 9.6, "max": 63.8, "step": 0.5, "group": 'Pocket', "label": 'Pocket height (mm)'},
    "filleted2": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "side_tube_d": {"type": 'float', "default": 12.8, "min": 5.1, "max": 22.5, "step": 1.0, "group": 'Side Tube', "label": 'Side tube diameter (mm)'},
    "side_tube_len": {"type": 'float', "default": 13.9, "min": 4.2, "max": 38.4, "step": 1.0, "group": 'Side Tube', "label": 'Side tube length (mm)'},
    "side_bore_d": {"type": 'float', "default": 5.8, "min": 2.0, "max": 9.6, "step": 0.5, "group": 'Side Tube', "label": 'Side bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["pocket_w"], p["pocket_d"])
        .cutBlind(-p["pocket_h"])
    )
    if p["filleted2"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.07746535564664443)
    result = (
        result.faces('>Y').workplane()
        .circle(p["side_tube_d"] / 2).extrude(p["side_tube_len"])
    )
    result = (
        result.faces('>Y').workplane()
        .hole(p["side_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
