import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004007 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 39.8, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 18.0, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 68.2, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "hole_d": {"type": 'float', "default": 3.8, "min": 2.0, "max": 5.3, "step": 0.5, "group": 'Holes', "label": 'Square hole size (mm)'},
    "pocket_w": {"type": 'float', "default": 17.3, "min": 8.7, "max": 31.8, "step": 1.0, "group": 'Pocket', "label": 'Pocket width (mm)'},
    "pocket_d": {"type": 'float', "default": 10.8, "min": 5.4, "max": 14.4, "step": 1.0, "group": 'Pocket', "label": 'Pocket depth (mm)'},
    "pocket_h": {"type": 'float', "default": 23.1, "min": 9.2, "max": 58.0, "step": 0.5, "group": 'Pocket', "label": 'Pocket height (mm)'},
    "filleted2": {"type": 'bool', "default": False, "group": 'Body', "label": 'Fillet corners'},
    "side_tube_d": {"type": 'float', "default": 9.8, "min": 3.9, "max": 19.9, "step": 1.0, "group": 'Side Tube', "label": 'Side tube diameter (mm)'},
    "side_tube_len": {"type": 'float', "default": 10.6, "min": 3.2, "max": 29.4, "step": 1.0, "group": 'Side Tube', "label": 'Side tube length (mm)'},
    "side_bore_d": {"type": 'float', "default": 4.7, "min": 2.0, "max": 7.4, "step": 0.5, "group": 'Side Tube', "label": 'Side bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().rect(p["hole_d"], p["hole_d"]).cutThruAll()
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["pocket_w"], p["pocket_d"])
        .cutBlind(-p["pocket_h"])
    )
    if p["filleted2"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.043009361428461686)
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .circle(p["side_tube_d"] / 2).extrude(p["side_tube_len"])
    )
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .hole(p["side_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
