import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234004432 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 52.85, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 40.2, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 100.0, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "hole_d": {"type": 'float', "default": 5.2, "min": 2.0, "max": 11.8, "step": 0.5, "group": 'Holes', "label": 'Square hole size (mm)'},
    "boss_d": {"type": 'float', "default": 25.0, "min": 12.5, "max": 50.0, "step": 1.0, "group": 'Boss', "label": 'Boss diameter (mm)'},
    "boss_h": {"type": 'float', "default": 6.0, "min": 2.4, "max": 15.0, "step": 1.0, "group": 'Boss', "label": 'Boss height (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().rect(p["hole_d"], p["hole_d"]).cutThruAll()
    )
    result = (
        result.faces('>Z').workplane()
        .circle(p["boss_d"] / 2).extrude(p["boss_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
