import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004450 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 16.08, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 6.5, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 10.7, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "bolt_d": {"type": 'float', "default": 4.3, "min": 3.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Bolt hole diameter (mm)'},
    "bolt_r": {"type": 'float', "default": 4.8, "min": 3.2, "max": 7.2, "step": 1.0, "group": 'Holes', "label": 'Bolt circle radius (mm)'},
    "n_bolts": {"type": 'int', "default": 6, "min": 3, "max": 12, "step": 1, "group": 'Holes', "label": 'Number of bolts'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .polarArray(p["bolt_r"], 0, 360, p["n_bolts"])
        .hole(p["bolt_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
