import cadquery as cq

# Generated by CadQuarry v0.1.0 — seed 1234004294 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 50, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 37.5, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 80.5, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "hole_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 8.4, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "pocket_w": {"type": 'float', "default": 26.2, "min": 13.1, "max": 40.0, "step": 1.0, "group": 'Pocket', "label": 'Pocket width (mm)'},
    "pocket_d": {"type": 'float', "default": 24.2, "min": 12.1, "max": 30.0, "step": 1.0, "group": 'Pocket', "label": 'Pocket depth (mm)'},
    "pocket_h": {"type": 'float', "default": 39.2, "min": 15.7, "max": 68.4, "step": 0.5, "group": 'Pocket', "label": 'Pocket height (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["pocket_w"], p["pocket_d"])
        .cutBlind(-p["pocket_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
