import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234003901 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 50, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 36.6, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 65.0, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "hole_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 3.7, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "hole_nx": {"type": 'int', "default": 5, "min": 2, "max": 5, "step": 1, "group": 'Holes', "label": 'Holes per row'},
    "pocket_w": {"type": 'float', "default": 34.2, "min": 17.1, "max": 40.0, "step": 1.0, "group": 'Pocket', "label": 'Pocket width (mm)'},
    "pocket_d": {"type": 'float', "default": 19.7, "min": 9.8, "max": 29.3, "step": 1.0, "group": 'Pocket', "label": 'Pocket depth (mm)'},
    "pocket_h": {"type": 'float', "default": 26.0, "min": 10.4, "max": 55.2, "step": 0.5, "group": 'Pocket', "label": 'Pocket height (mm)'},
    "filleted2": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "side_tube_d": {"type": 'float', "default": 7.3, "min": 2.9, "max": 18.3, "step": 1.0, "group": 'Side Tube', "label": 'Side tube diameter (mm)'},
    "side_tube_len": {"type": 'float', "default": 9.8, "min": 2.9, "max": 21.9, "step": 1.0, "group": 'Side Tube', "label": 'Side tube length (mm)'},
    "side_bore_d": {"type": 'float', "default": 4.0, "min": 2.0, "max": 5.5, "step": 0.5, "group": 'Side Tube', "label": 'Side bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    _snx = max(2, int(p["hole_nx"]))
    _ssx = 9.4
    _ssy = 9.8
    _spts = (
        [(-_ssx * (_snx - 1) / 2 + _ssx * _i, -_ssy / 2) for _i in range(_snx)]
        + [(-_ssx * (_snx - 2) / 2 + _ssx * _i, _ssy / 2) for _i in range(_snx - 1)]
    )
    result = (
        result.faces('>Z').workplane()
        .pushPoints(_spts)
        .hole(p["hole_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["pocket_w"], p["pocket_d"])
        .cutBlind(-p["pocket_h"])
    )
    if p["filleted2"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.11845776627979887)
    result = (
        result.faces('>X').workplane()
        .circle(p["side_tube_d"] / 2).extrude(p["side_tube_len"])
    )
    result = (
        result.faces('>X').workplane()
        .hole(p["side_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
