import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004654 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 94.32, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 53.5, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 100.0, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "bolt_d": {"type": 'float', "default": 3.2, "min": 3.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Bolt hole diameter (mm)'},
    "bolt_r": {"type": 'float', "default": 28.3, "min": 18.9, "max": 42.4, "step": 1.0, "group": 'Holes', "label": 'Bolt circle radius (mm)'},
    "n_bolts": {"type": 'int', "default": 12, "min": 3, "max": 12, "step": 1, "group": 'Holes', "label": 'Number of bolts'},
    "pocket_w": {"type": 'float', "default": 57.4, "min": 28.7, "max": 75.5, "step": 1.0, "group": 'Pocket', "label": 'Pocket width (mm)'},
    "pocket_d": {"type": 'float', "default": 30.7, "min": 15.3, "max": 42.8, "step": 1.0, "group": 'Pocket', "label": 'Pocket depth (mm)'},
    "pocket_h": {"type": 'float', "default": 54.9, "min": 22.0, "max": 85.0, "step": 0.5, "group": 'Pocket', "label": 'Pocket height (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .polarArray(p["bolt_r"], 0, 360, p["n_bolts"])
        .hole(p["bolt_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["pocket_w"], p["pocket_d"])
        .cutBlind(-p["pocket_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
