import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234004287 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 48.06, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 26.3, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 51.7, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "hole_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 5.9, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "filleted2": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "side_tube_d": {"type": 'float', "default": 18.1, "min": 7.2, "max": 24.0, "step": 1.0, "group": 'Side Tube', "label": 'Side tube diameter (mm)'},
    "side_tube_len": {"type": 'float', "default": 31.7, "min": 9.5, "max": 54.3, "step": 1.0, "group": 'Side Tube', "label": 'Side tube length (mm)'},
    "side_bore_d": {"type": 'float', "default": 11.2, "min": 2.0, "max": 13.6, "step": 0.5, "group": 'Side Tube', "label": 'Side bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.07547148831029854)
    if p["filleted2"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.062087270466778074)
    result = (
        result.faces('>Y').workplane()
        .circle(p["side_tube_d"] / 2).extrude(p["side_tube_len"])
    )
    result = (
        result.faces('>Y').workplane()
        .hole(p["side_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
