import cadquery as cq

# Generated by CadQuarry v0.1.0 — seed 1234003997 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 75, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 60.2, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 67.0, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "hole_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "boss_d": {"type": 'float', "default": 10.5, "min": 5.2, "max": 21.0, "step": 1.0, "group": 'Boss', "label": 'Boss diameter (mm)'},
    "boss_h": {"type": 'float', "default": 4.6, "min": 1.8, "max": 11.5, "step": 1.0, "group": 'Boss', "label": 'Boss height (mm)'},
    "boss_bore_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 7.3, "step": 0.1, "group": 'Boss', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .circle(p["boss_d"] / 2).extrude(p["boss_h"])
    )
    result = (
        result.faces('>Z').workplane()
        .hole(p["boss_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
