import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234003947 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 65, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 40.8, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 98.8, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "hole_d": {"type": 'float', "default": 7.7, "min": 2.0, "max": 11.9, "step": 0.5, "group": 'Holes', "label": 'Square hole size (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "filleted2": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "side_tube_d": {"type": 'float', "default": 8.3, "min": 3.3, "max": 20.4, "step": 1.0, "group": 'Side Tube', "label": 'Side tube diameter (mm)'},
    "side_tube_len": {"type": 'float', "default": 15.0, "min": 4.5, "max": 24.9, "step": 1.0, "group": 'Side Tube', "label": 'Side tube length (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().rect(p["hole_d"], p["hole_d"]).cutThruAll()
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.08375441402403905)
    if p["filleted2"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.06933525982548919)
    result = (
        result.faces('<X').workplane()
        .circle(p["side_tube_d"] / 2).extrude(p["side_tube_len"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
