import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004533 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 15.57, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 10.1, "min": 6.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 10.0, "min": 4.5, "max": 200.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "hole_d": {"type": 'float', "default": 2.1, "min": 2.0, "max": 2.3, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "pocket_w": {"type": 'float', "default": 6.4, "min": 3.2, "max": 12.5, "step": 1.0, "group": 'Pocket', "label": 'Pocket width (mm)'},
    "pocket_d": {"type": 'float', "default": 4.1, "min": 2.0, "max": 8.1, "step": 1.0, "group": 'Pocket', "label": 'Pocket depth (mm)'},
    "pocket_h": {"type": 'float', "default": 4.5, "min": 1.8, "max": 8.5, "step": 0.5, "group": 'Pocket', "label": 'Pocket height (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["pocket_w"], p["pocket_d"])
        .cutBlind(-p["pocket_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
