import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004576 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_sides": {"type": 'int', "default": 6, "min": 3, "max": 8, "step": 1, "group": 'Base', "label": 'Base sides'},
    "base_r": {"type": 'float', "default": 10.0, "min": 6.0, "max": 16.0, "step": 1.0, "group": 'Base', "label": 'Base circumradius (mm)'},
    "base_h": {"type": 'float', "default": 5.4, "min": 2.2, "max": 13.5, "step": 1.0, "group": 'Base', "label": 'Base height (mm)'},
    "col_d": {"type": 'float', "default": 9.5, "min": 4.8, "max": 13.9, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 10.6, "min": 3.2, "max": 26.5, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["base_sides"], p["base_r"] * 2).extrude(p["base_h"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["base_r"], p["base_r"]) * 0.08088296797427619)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
