import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004585 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "adapter_base": {"type": 'float', "default": 51.51, "min": 30.9, "max": 77.3, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "adapter_top": {"type": 'float', "default": 25.4, "min": 12.7, "max": 51.5, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "adapter_h": {"type": 'float', "default": 56.1, "min": 22.4, "max": 112.2, "step": 1.0, "group": 'Body', "label": 'Transition height (mm)'},
    "neck_d": {"type": 'float', "default": 19.1, "min": 7.6, "max": 25.4, "step": 1.0, "group": 'Neck', "label": 'Neck diameter (mm)'},
    "neck_l": {"type": 'float', "default": 20.8, "min": 8.3, "max": 52.0, "step": 1.0, "group": 'Neck', "label": 'Neck length (mm)'},
    "neck_bore": {"type": 'float', "default": 8.3, "min": 2.0, "max": 13.8, "step": 0.5, "group": 'Neck', "label": 'Neck bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .circle(p["adapter_base"] / 2)
        .workplane(offset=p["adapter_h"])
        .rect(p["adapter_top"], p["adapter_top"])
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["neck_d"] / 2).extrude(p["neck_l"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["neck_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
