import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004562 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_sides": {"type": 'int', "default": 8, "min": 3, "max": 8, "step": 1, "group": 'Base', "label": 'Base sides'},
    "base_r": {"type": 'float', "default": 24.09, "min": 14.5, "max": 38.5, "step": 1.0, "group": 'Base', "label": 'Base circumradius (mm)'},
    "base_h": {"type": 'float', "default": 15.8, "min": 6.3, "max": 39.5, "step": 1.0, "group": 'Base', "label": 'Base height (mm)'},
    "col_d": {"type": 'float', "default": 24.4, "min": 12.2, "max": 35.6, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 25.4, "min": 7.6, "max": 63.5, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
    "col_bore": {"type": 'float', "default": 14.3, "min": 2.0, "max": 17.6, "step": 0.5, "group": 'Column', "label": 'Column bore diameter (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["base_sides"], p["base_r"] * 2).extrude(p["base_h"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["col_bore"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["base_r"], p["base_r"]) * 0.10098298132895267)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
