import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003730 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 55, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body width (mm)'},
    "block_d": {"type": 'float', "default": 58.6, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body depth (mm)'},
    "block_h": {"type": 'float', "default": 46.3, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body height (mm)'},
    "port_d": {"type": 'float', "default": 11.4, "min": 4.6, "max": 20.8, "step": 1.0, "group": 'Ports', "label": 'Ports diameter (mm)'},
    "port_len": {"type": 'float', "default": 5.9, "min": 2.9, "max": 34.2, "step": 1.0, "group": 'Ports', "label": 'Port boss length (mm)'},
    "port_bore": {"type": 'float', "default": 7.0, "min": 2.0, "max": 8.2, "step": 0.5, "group": 'Ports', "label": 'Port bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<X').workplane(centerOption='CenterOfBoundBox')
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('<X').workplane(centerOption='CenterOfBoundBox')
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>Y').workplane(centerOption='CenterOfBoundBox')
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>Y').workplane(centerOption='CenterOfBoundBox')
        .hole(p["port_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
