import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234003864 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 40.13, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body width (mm)'},
    "block_d": {"type": 'float', "default": 34.8, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body depth (mm)'},
    "block_h": {"type": 'float', "default": 30.2, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body height (mm)'},
    "port_sides": {"type": 'int', "default": 8, "min": 3, "max": 8, "step": 1, "group": 'Ports', "label": 'Ports sides'},
    "port_r": {"type": 'float', "default": 3.6, "min": 1.8, "max": 6.8, "step": 1.0, "group": 'Ports', "label": 'Ports circumradius (mm)'},
    "port_len": {"type": 'float', "default": 8.8, "min": 1.7, "max": 20.0, "step": 1.0, "group": 'Ports', "label": 'Port boss length (mm)'},
    "port_bore": {"type": 'float', "default": 3.2, "min": 2.0, "max": 4.8, "step": 0.5, "group": 'Ports', "label": 'Port bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .polygon(p["port_sides"], p["port_r"] * 2).extrude(p["port_len"])
    )
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>X').workplane(centerOption='CenterOfBoundBox')
        .polygon(p["port_sides"], p["port_r"] * 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>X').workplane(centerOption='CenterOfBoundBox')
        .hole(p["port_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
