import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004620 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 88.8, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body width (mm)'},
    "block_d": {"type": 'float', "default": 89.8, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body depth (mm)'},
    "block_h": {"type": 'float', "default": 80.5, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body height (mm)'},
    "port_d": {"type": 'float', "default": 23.0, "min": 9.2, "max": 36.2, "step": 1.0, "group": 'Ports', "label": 'Ports diameter (mm)'},
    "port_len": {"type": 'float', "default": 13.7, "min": 5.8, "max": 69.0, "step": 1.0, "group": 'Ports', "label": 'Port boss length (mm)'},
    "port_bore": {"type": 'float', "default": 11.7, "min": 2.0, "max": 16.6, "step": 0.5, "group": 'Ports', "label": 'Port bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>X').workplane(centerOption='CenterOfBoundBox')
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>X').workplane(centerOption='CenterOfBoundBox')
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>Y').workplane(centerOption='CenterOfBoundBox')
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>Y').workplane(centerOption='CenterOfBoundBox')
        .hole(p["port_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
