import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004785 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_sides": {"type": 'int', "default": 8, "min": 3, "max": 8, "step": 1, "group": 'Base', "label": 'Base sides'},
    "base_r": {"type": 'float', "default": 28.43, "min": 17.1, "max": 45.5, "step": 1.0, "group": 'Base', "label": 'Base circumradius (mm)'},
    "base_h": {"type": 'float', "default": 21.5, "min": 8.6, "max": 53.8, "step": 1.0, "group": 'Base', "label": 'Base height (mm)'},
    "col_d": {"type": 'float', "default": 25.9, "min": 12.9, "max": 42.0, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 31.2, "min": 9.4, "max": 78.0, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["base_sides"], p["base_r"] * 2).extrude(p["base_h"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["base_r"], p["base_r"]) * 0.05280602762832996)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
