import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004497 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_sides": {"type": 'int', "default": 8, "min": 3, "max": 8, "step": 1, "group": 'Base', "label": 'Base sides'},
    "base_r": {"type": 'float', "default": 25, "min": 15.0, "max": 40.0, "step": 1.0, "group": 'Base', "label": 'Base circumradius (mm)'},
    "base_h": {"type": 'float', "default": 11.8, "min": 4.7, "max": 29.5, "step": 1.0, "group": 'Base', "label": 'Base height (mm)'},
    "col_d": {"type": 'float', "default": 28.2, "min": 14.1, "max": 37.0, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 29.1, "min": 8.7, "max": 72.8, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
    "col_bore": {"type": 'float', "default": 13.7, "min": 2.0, "max": 20.3, "step": 0.5, "group": 'Column', "label": 'Column bore diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["base_sides"], p["base_r"] * 2).extrude(p["base_h"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["col_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
