import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003775 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "adapter_base": {"type": 'float', "default": 69.61, "min": 41.8, "max": 104.4, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "adapter_top": {"type": 'float', "default": 38.6, "min": 19.3, "max": 69.6, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "adapter_h": {"type": 'float', "default": 59.6, "min": 23.8, "max": 119.2, "step": 1.0, "group": 'Body', "label": 'Transition height (mm)'},
    "adapter_mid": {"type": 'float', "default": 54.1, "min": 19.3, "max": 69.6, "step": 1.0, "group": 'Body', "label": 'Mid size (mm)'},
    "neck_sides": {"type": 'int', "default": 6, "min": 3, "max": 8, "step": 1, "group": 'Neck', "label": 'Neck sides'},
    "neck_r": {"type": 'float', "default": 14.8, "min": 7.4, "max": 19.3, "step": 1.0, "group": 'Neck', "label": 'Neck circumradius (mm)'},
    "neck_l": {"type": 'float', "default": 21.0, "min": 8.4, "max": 52.5, "step": 1.0, "group": 'Neck', "label": 'Neck length (mm)'},
    "neck_bore": {"type": 'float', "default": 13.3, "min": 2.0, "max": 18.5, "step": 0.5, "group": 'Neck', "label": 'Neck bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .rect(p["adapter_base"], p["adapter_base"])
        .workplane(offset=p["adapter_h"] * 0.5)
        .circle(p["adapter_mid"] / 2)
        .workplane(offset=p["adapter_h"] * 0.5)
        .circle(p["adapter_top"] / 2)
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .polygon(p["neck_sides"], p["neck_r"] * 2).extrude(p["neck_l"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["neck_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
