import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004600 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 40, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 36.5, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 39.9, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "tab_a": {"type": 'float', "default": 33.7, "min": 13.5, "max": 53.9, "step": 1.0, "group": 'Tab', "label": 'Tab width (mm)'},
    "tab_b": {"type": 'float', "default": 26.4, "min": 10.6, "max": 42.2, "step": 1.0, "group": 'Tab', "label": 'Tab height (mm)'},
    "tab_t": {"type": 'float', "default": 8.0, "min": 2.0, "max": 15.0, "step": 0.5, "group": 'Tab', "label": 'Tab thickness (mm)'},
    "tab_hole_d": {"type": 'float', "default": 5.3, "min": 2.0, "max": 5.8, "step": 0.1, "group": 'Tab', "label": 'Tab hole diameter (mm)'},
    "pocket_w": {"type": 'float', "default": 21.1, "min": 10.6, "max": 32.0, "step": 1.0, "group": 'Pocket', "label": 'Pocket width (mm)'},
    "pocket_d": {"type": 'float', "default": 16.4, "min": 8.2, "max": 29.2, "step": 1.0, "group": 'Pocket', "label": 'Pocket depth (mm)'},
    "pocket_h": {"type": 'float', "default": 22.3, "min": 8.9, "max": 33.9, "step": 0.5, "group": 'Pocket', "label": 'Pocket height (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>X').workplane(centerOption='CenterOfBoundBox')
        .rect(p["tab_a"], p["tab_b"]).extrude(p["tab_t"])
    )
    result = (
        result.faces('>X').workplane()
        .rect(p["tab_a"] * 0.6, p["tab_b"] * 0.6, forConstruction=True)
        .vertices().hole(p["tab_hole_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["pocket_w"], p["pocket_d"])
        .cutBlind(-p["pocket_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
