import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234003828 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "shaft_d": {"type": 'float', "default": 25, "min": 12.5, "max": 45.0, "step": 1.0, "group": 'Body', "label": 'Shaft diameter (mm)'},
    "shaft_len": {"type": 'float', "default": 26.2, "min": 10.5, "max": 52.4, "step": 1.0, "group": 'Body', "label": 'Shaft length (mm)'},
    "step_d": {"type": 'float', "default": 12.2, "min": 6.1, "max": 22.5, "step": 1.0, "group": 'Step', "label": 'Step diameter (mm)'},
    "step_len": {"type": 'float', "default": 13.3, "min": 4.0, "max": 33.2, "step": 1.0, "group": 'Step', "label": 'Step length (mm)'},
    "axial_bore": {"type": 'float', "default": 5.5, "min": 2.0, "max": 8.8, "step": 0.5, "group": 'Bore', "label": 'Axial bore diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').circle(p["shaft_d"] / 2).extrude(p["shaft_len"]))
    result = (
        result.faces('>Z').workplane()
        .circle(p["step_d"] / 2).extrude(p["step_len"])
    )
    result = (
        result.faces('>Z').workplane()
        .hole(p["axial_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
