import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004108 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 21.15, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 20.7, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 17.6, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_a": {"type": 'float', "default": 7.6, "min": 3.8, "max": 12.3, "step": 1.0, "group": 'Spigot', "label": 'Spigot width (mm)'},
    "spig_b": {"type": 'float', "default": 6.0, "min": 3.0, "max": 12.3, "step": 1.0, "group": 'Spigot', "label": 'Spigot depth (mm)'},
    "spig_len": {"type": 'float', "default": 13.7, "min": 1.8, "max": 24.0, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
    "spig_bore": {"type": 'float', "default": 3.0, "min": 2.0, "max": 4.3, "step": 0.5, "group": 'Spigot', "label": 'Bore diameter (mm)'},
    "hole_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 4.7, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<X').workplane(centerOption='CenterOfBoundBox')
        .rect(p["spig_a"], p["spig_b"]).extrude(p["spig_len"])
    )
    result = (
        result.faces('<X').workplane(centerOption='CenterOfBoundBox')
        .hole(p["spig_bore"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
