import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234003812 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "shaft_d": {"type": 'float', "default": 41.72, "min": 20.9, "max": 75.1, "step": 1.0, "group": 'Body', "label": 'Shaft diameter (mm)'},
    "shaft_len": {"type": 'float', "default": 35.0, "min": 14.0, "max": 70.0, "step": 1.0, "group": 'Body', "label": 'Shaft length (mm)'},
    "step_d": {"type": 'float', "default": 19.9, "min": 9.9, "max": 37.5, "step": 1.0, "group": 'Step', "label": 'Step diameter (mm)'},
    "step_len": {"type": 'float', "default": 25.1, "min": 7.5, "max": 62.8, "step": 1.0, "group": 'Step', "label": 'Step length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').circle(p["shaft_d"] / 2).extrude(p["shaft_len"]))
    result = (
        result.faces('>Z').workplane()
        .circle(p["step_d"] / 2).extrude(p["step_len"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
