import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004598 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "adapter_base": {"type": 'float', "default": 55, "min": 33.0, "max": 82.5, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "adapter_top": {"type": 'float', "default": 28.3, "min": 14.2, "max": 55, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "adapter_h": {"type": 'float', "default": 57.9, "min": 23.2, "max": 115.8, "step": 1.0, "group": 'Body', "label": 'Transition height (mm)'},
    "neck_d": {"type": 'float', "default": 20.4, "min": 8.2, "max": 28.3, "step": 1.0, "group": 'Neck', "label": 'Neck diameter (mm)'},
    "neck_l": {"type": 'float', "default": 15.2, "min": 6.1, "max": 38.0, "step": 1.0, "group": 'Neck', "label": 'Neck length (mm)'},
    "neck_bore": {"type": 'float', "default": 11.4, "min": 2.0, "max": 14.7, "step": 0.5, "group": 'Neck', "label": 'Neck bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .rect(p["adapter_base"], p["adapter_base"])
        .workplane(offset=p["adapter_h"])
        .circle(p["adapter_top"] / 2)
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["neck_d"] / 2).extrude(p["neck_l"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["neck_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
