import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004191 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 60, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body width (mm)'},
    "block_d": {"type": 'float', "default": 54.9, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body depth (mm)'},
    "block_h": {"type": 'float', "default": 52.7, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body height (mm)'},
    "port_sides": {"type": 'int', "default": 6, "min": 3, "max": 8, "step": 1, "group": 'Ports', "label": 'Ports sides'},
    "port_r": {"type": 'float', "default": 5.2, "min": 2.6, "max": 11.8, "step": 1.0, "group": 'Ports', "label": 'Ports circumradius (mm)'},
    "port_len": {"type": 'float', "default": 10.1, "min": 2.3, "max": 27.0, "step": 1.0, "group": 'Ports', "label": 'Port boss length (mm)'},
    "port_bore": {"type": 'float', "default": 4.7, "min": 2.0, "max": 6.5, "step": 0.5, "group": 'Ports', "label": 'Port bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>X').workplane()
        .polygon(p["port_sides"], p["port_r"] * 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>X').workplane()
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>Y').workplane()
        .polygon(p["port_sides"], p["port_r"] * 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>Y').workplane()
        .hole(p["port_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
