import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004064 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 65, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 61.9, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 63.5, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "tab_a": {"type": 'float', "default": 48.3, "min": 19.3, "max": 77.3, "step": 1.0, "group": 'Tab', "label": 'Tab width (mm)'},
    "tab_b": {"type": 'float', "default": 37.1, "min": 14.8, "max": 59.4, "step": 1.0, "group": 'Tab', "label": 'Tab height (mm)'},
    "tab_t": {"type": 'float', "default": 8.0, "min": 2.0, "max": 15.0, "step": 0.5, "group": 'Tab', "label": 'Tab thickness (mm)'},
    "tab_hole_d": {"type": 'float', "default": 6.4, "min": 2.0, "max": 8.2, "step": 0.1, "group": 'Tab', "label": 'Tab hole diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .rect(p["tab_a"], p["tab_b"]).extrude(p["tab_t"])
    )
    result = (
        result.faces('<Y').workplane()
        .rect(p["tab_a"] * 0.6, p["tab_b"] * 0.6, forConstruction=True)
        .vertices().hole(p["tab_hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
