import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004210 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_w": {"type": 'float', "default": 97.11, "min": 30.0, "max": 160.0, "step": 1.0, "group": 'Base', "label": 'Base width (mm)'},
    "base_d": {"type": 'float', "default": 59.4, "min": 25.0, "max": 160.0, "step": 1.0, "group": 'Base', "label": 'Base depth (mm)'},
    "base_h": {"type": 'float', "default": 10.0, "min": 3.0, "max": 30.0, "step": 0.5, "group": 'Base', "label": 'Base thickness (mm)'},
    "col_d": {"type": 'float', "default": 19.6, "min": 7.8, "max": 29.7, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 38.7, "min": 11.6, "max": 116.1, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
    "hole_d": {"type": 'float', "default": 8.4, "min": 2.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["base_w"], p["base_d"], p["base_h"])
    result = (
        result.faces('>Z').workplane()
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["base_w"] * 0.7, p["base_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
