import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004137 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "shaft_d": {"type": 'float', "default": 31.83, "min": 15.9, "max": 57.3, "step": 1.0, "group": 'Body', "label": 'Shaft diameter (mm)'},
    "shaft_len": {"type": 'float', "default": 61.0, "min": 24.4, "max": 122.0, "step": 1.0, "group": 'Body', "label": 'Shaft length (mm)'},
    "step_d": {"type": 'float', "default": 18.7, "min": 9.3, "max": 28.6, "step": 1.0, "group": 'Step', "label": 'Step diameter (mm)'},
    "step_len": {"type": 'float', "default": 48.9, "min": 14.7, "max": 122.2, "step": 1.0, "group": 'Step', "label": 'Step length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').circle(p["shaft_d"] / 2).extrude(p["shaft_len"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["step_d"] / 2).extrude(p["step_len"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
