import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004164 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_w": {"type": 'float', "default": 84.86, "min": 30.0, "max": 160.0, "step": 1.0, "group": 'Base', "label": 'Base width (mm)'},
    "base_d": {"type": 'float', "default": 71.1, "min": 25.0, "max": 160.0, "step": 1.0, "group": 'Base', "label": 'Base depth (mm)'},
    "base_h": {"type": 'float', "default": 10.0, "min": 3.0, "max": 30.0, "step": 0.5, "group": 'Base', "label": 'Base thickness (mm)'},
    "col_d": {"type": 'float', "default": 12.9, "min": 5.2, "max": 35.5, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 105.9, "min": 31.8, "max": 317.7, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
    "col_bore": {"type": 'float', "default": 5.9, "min": 2.0, "max": 9.3, "step": 0.5, "group": 'Column', "label": 'Column bore diameter (mm)'},
    "hole_d": {"type": 'float', "default": 8.4, "min": 2.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = cq.Workplane('XY').box(p["base_w"], p["base_d"], p["base_h"])
    result = (
        result.faces('>Z').workplane()
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    result = (
        result.faces('>Z').workplane()
        .hole(p["col_bore"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["base_w"] * 0.7, p["base_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["base_w"], p["base_d"]) * 0.11021388833554621)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
