import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004484 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "shaft_d": {"type": 'float', "default": 24.18, "min": 12.1, "max": 43.5, "step": 1.0, "group": 'Body', "label": 'Shaft diameter (mm)'},
    "shaft_len": {"type": 'float', "default": 38.4, "min": 15.4, "max": 76.8, "step": 1.0, "group": 'Body', "label": 'Shaft length (mm)'},
    "step_d": {"type": 'float', "default": 11.9, "min": 6.0, "max": 21.8, "step": 1.0, "group": 'Step', "label": 'Step diameter (mm)'},
    "step_len": {"type": 'float', "default": 25.5, "min": 7.6, "max": 63.8, "step": 1.0, "group": 'Step', "label": 'Step length (mm)'},
    "axial_bore": {"type": 'float', "default": 5.8, "min": 2.0, "max": 8.6, "step": 0.5, "group": 'Bore', "label": 'Axial bore diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').circle(p["shaft_d"] / 2).extrude(p["shaft_len"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["step_d"] / 2).extrude(p["step_len"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["axial_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
