import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234003826 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_sides": {"type": 'int', "default": 8, "min": 3, "max": 8, "step": 1, "group": 'Base', "label": 'Base sides'},
    "base_r": {"type": 'float', "default": 10.0, "min": 6.0, "max": 16.0, "step": 1.0, "group": 'Base', "label": 'Base circumradius (mm)'},
    "base_h": {"type": 'float', "default": 11.7, "min": 4.7, "max": 29.2, "step": 1.0, "group": 'Base', "label": 'Base height (mm)'},
    "col_d": {"type": 'float', "default": 11.8, "min": 5.9, "max": 14.8, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 22.1, "min": 6.6, "max": 55.2, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["base_sides"], p["base_r"] * 2).extrude(p["base_h"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["base_r"], p["base_r"]) * 0.10662041512286091)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
