import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004605 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_sides": {"type": 'int', "default": 5, "min": 3, "max": 8, "step": 1, "group": 'Base', "label": 'Base sides'},
    "base_r": {"type": 'float', "default": 15, "min": 9.0, "max": 24.0, "step": 1.0, "group": 'Base', "label": 'Base circumradius (mm)'},
    "base_h": {"type": 'float', "default": 9.4, "min": 3.8, "max": 23.5, "step": 1.0, "group": 'Base', "label": 'Base height (mm)'},
    "col_d": {"type": 'float', "default": 11.0, "min": 5.5, "max": 19.4, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 15.0, "min": 4.5, "max": 37.5, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["base_sides"], p["base_r"] * 2).extrude(p["base_h"]))
    result = (
        result.faces('>Z').workplane()
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
