import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004301 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 20.0, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 22.0, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 20.1, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_sides": {"type": 'int', "default": 5, "min": 3, "max": 8, "step": 1, "group": 'Spigot', "label": 'Spigot sides'},
    "spig_r": {"type": 'float', "default": 3.1, "min": 1.6, "max": 7.0, "step": 1.0, "group": 'Spigot', "label": 'Spigot circumradius (mm)'},
    "spig_len": {"type": 'float', "default": 12.1, "min": 1.5, "max": 20.1, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>X').workplane(centerOption='CenterOfBoundBox')
        .polygon(p["spig_sides"], p["spig_r"] * 2).extrude(p["spig_len"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
