import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004557 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "shaft_d": {"type": 'float', "default": 48.2, "min": 24.1, "max": 86.8, "step": 1.0, "group": 'Body', "label": 'Shaft diameter (mm)'},
    "shaft_len": {"type": 'float', "default": 75.4, "min": 30.2, "max": 150.8, "step": 1.0, "group": 'Body', "label": 'Shaft length (mm)'},
    "step_d": {"type": 'float', "default": 23.1, "min": 11.6, "max": 43.4, "step": 1.0, "group": 'Step', "label": 'Step diameter (mm)'},
    "step_len": {"type": 'float', "default": 38.3, "min": 11.5, "max": 95.8, "step": 1.0, "group": 'Step', "label": 'Step length (mm)'},
    "head_sides": {"type": 'int', "default": 6, "min": 3, "max": 8, "step": 1, "group": 'Head', "label": 'Drive head sides'},
    "head_r": {"type": 'float', "default": 10.0, "min": 6.0, "max": 11.1, "step": 1.0, "group": 'Head', "label": 'Drive head circumradius (mm)'},
    "head_len": {"type": 'float', "default": 9.8, "min": 2.9, "max": 19.6, "step": 1.0, "group": 'Head', "label": 'Drive head length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').circle(p["shaft_d"] / 2).extrude(p["shaft_len"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["step_d"] / 2).extrude(p["step_len"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .polygon(p["head_sides"], p["head_r"] * 2).extrude(p["head_len"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
