import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234003879 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 20.0, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 25.1, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 15.0, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_sides": {"type": 'int', "default": 6, "min": 3, "max": 8, "step": 1, "group": 'Spigot', "label": 'Spigot sides'},
    "spig_r": {"type": 'float', "default": 3.0, "min": 1.5, "max": 5.2, "step": 1.0, "group": 'Spigot', "label": 'Spigot circumradius (mm)'},
    "spig_len": {"type": 'float', "default": 11.3, "min": 1.6, "max": 20.8, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
    "spig_bore": {"type": 'float', "default": 2.4, "min": 2.0, "max": 3.7, "step": 0.5, "group": 'Spigot', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<Y').workplane()
        .polygon(p["spig_sides"], p["spig_r"] * 2).extrude(p["spig_len"])
    )
    result = (
        result.faces('<Y').workplane()
        .hole(p["spig_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
