import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004198 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 60.98, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 60.3, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 34.8, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_a": {"type": 'float', "default": 9.3, "min": 4.7, "max": 24.4, "step": 1.0, "group": 'Spigot', "label": 'Spigot width (mm)'},
    "spig_b": {"type": 'float', "default": 6.0, "min": 3.0, "max": 24.4, "step": 1.0, "group": 'Spigot', "label": 'Spigot depth (mm)'},
    "spig_len": {"type": 'float', "default": 6.1, "min": 1.8, "max": 24.0, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<X').workplane()
        .rect(p["spig_a"], p["spig_b"]).extrude(p["spig_len"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
