import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004541 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 60, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 31.3, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 43.4, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_d": {"type": 'float', "default": 16.1, "min": 6.4, "max": 30.4, "step": 1.0, "group": 'Spigot', "label": 'Spigot diameter (mm)'},
    "spig_len": {"type": 'float', "default": 13.7, "min": 4.8, "max": 64.4, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
    "spig_bore": {"type": 'float', "default": 8.5, "min": 2.0, "max": 11.6, "step": 0.5, "group": 'Spigot', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .circle(p["spig_d"] / 2).extrude(p["spig_len"])
    )
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .hole(p["spig_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
