import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004356 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "shaft_d": {"type": 'float', "default": 48.61, "min": 24.3, "max": 87.5, "step": 1.0, "group": 'Body', "label": 'Shaft diameter (mm)'},
    "shaft_len": {"type": 'float', "default": 103.8, "min": 41.5, "max": 207.6, "step": 1.0, "group": 'Body', "label": 'Shaft length (mm)'},
    "step_d": {"type": 'float', "default": 22.2, "min": 11.1, "max": 43.7, "step": 1.0, "group": 'Step', "label": 'Step diameter (mm)'},
    "step_len": {"type": 'float', "default": 83.5, "min": 25.1, "max": 208.8, "step": 1.0, "group": 'Step', "label": 'Step length (mm)'},
    "axial_bore": {"type": 'float', "default": 11.6, "min": 2.0, "max": 16.0, "step": 0.5, "group": 'Bore', "label": 'Axial bore diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').circle(p["shaft_d"] / 2).extrude(p["shaft_len"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["step_d"] / 2).extrude(p["step_len"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["axial_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
