import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004742 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 70, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 58.7, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 72.5, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_sides": {"type": 'int', "default": 8, "min": 3, "max": 8, "step": 1, "group": 'Spigot', "label": 'Spigot sides'},
    "spig_r": {"type": 'float', "default": 9.4, "min": 4.7, "max": 24.5, "step": 1.0, "group": 'Spigot', "label": 'Spigot circumradius (mm)'},
    "spig_len": {"type": 'float', "default": 23.1, "min": 5.2, "max": 69.5, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
    "spig_bore": {"type": 'float', "default": 8.3, "min": 2.0, "max": 12.5, "step": 0.5, "group": 'Spigot', "label": 'Bore diameter (mm)'},
    "hole_d": {"type": 'float', "default": 5.3, "min": 2.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .polygon(p["spig_sides"], p["spig_r"] * 2).extrude(p["spig_len"])
    )
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .hole(p["spig_bore"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
