import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004558 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "shaft_d": {"type": 'float', "default": 21.26, "min": 10.6, "max": 38.3, "step": 1.0, "group": 'Body', "label": 'Shaft diameter (mm)'},
    "shaft_len": {"type": 'float', "default": 40.7, "min": 16.3, "max": 81.4, "step": 1.0, "group": 'Body', "label": 'Shaft length (mm)'},
    "step_d": {"type": 'float', "default": 15.3, "min": 7.7, "max": 19.1, "step": 1.0, "group": 'Step', "label": 'Step diameter (mm)'},
    "step_len": {"type": 'float', "default": 29.0, "min": 8.7, "max": 72.5, "step": 1.0, "group": 'Step', "label": 'Step length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').circle(p["shaft_d"] / 2).extrude(p["shaft_len"]))
    result = (
        result.faces('>Z').workplane()
        .circle(p["step_d"] / 2).extrude(p["step_len"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
