import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004272 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 25, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 18.1, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 27.6, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_sides": {"type": 'int', "default": 8, "min": 3, "max": 8, "step": 1, "group": 'Spigot', "label": 'Spigot sides'},
    "spig_r": {"type": 'float', "default": 4.7, "min": 2.4, "max": 8.8, "step": 1.0, "group": 'Spigot', "label": 'Spigot circumradius (mm)'},
    "spig_len": {"type": 'float', "default": 13.7, "min": 2.6, "max": 34.7, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
    "spig_bore": {"type": 'float', "default": 4.3, "min": 2.0, "max": 6.3, "step": 0.5, "group": 'Spigot', "label": 'Bore diameter (mm)'},
    "hole_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 4.1, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Y').workplane()
        .polygon(p["spig_sides"], p["spig_r"] * 2).extrude(p["spig_len"])
    )
    result = (
        result.faces('>Y').workplane()
        .hole(p["spig_bore"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.07598709827295981)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
