import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004005 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 37.85, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 39.3, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 39.4, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "tab_a": {"type": 'float', "default": 32.2, "min": 12.9, "max": 51.5, "step": 1.0, "group": 'Tab', "label": 'Tab width (mm)'},
    "tab_b": {"type": 'float', "default": 27.4, "min": 11.0, "max": 43.8, "step": 1.0, "group": 'Tab', "label": 'Tab height (mm)'},
    "tab_t": {"type": 'float', "default": 5.0, "min": 2.0, "max": 15.0, "step": 0.5, "group": 'Tab', "label": 'Tab thickness (mm)'},
    "tab_hole_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 6.0, "step": 0.1, "group": 'Tab', "label": 'Tab hole diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>X').workplane()
        .rect(p["tab_a"], p["tab_b"]).extrude(p["tab_t"])
    )
    result = (
        result.faces('>X').workplane()
        .rect(p["tab_a"] * 0.6, p["tab_b"] * 0.6, forConstruction=True)
        .vertices().hole(p["tab_hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
