import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004406 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 88.94, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body width (mm)'},
    "block_d": {"type": 'float', "default": 93.5, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body depth (mm)'},
    "block_h": {"type": 'float', "default": 68.5, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body height (mm)'},
    "port_d": {"type": 'float', "default": 18.1, "min": 7.2, "max": 30.8, "step": 1.0, "group": 'Ports', "label": 'Ports diameter (mm)'},
    "port_len": {"type": 'float', "default": 24.9, "min": 4.5, "max": 54.3, "step": 1.0, "group": 'Ports', "label": 'Port boss length (mm)'},
    "port_bore": {"type": 'float', "default": 8.9, "min": 2.0, "max": 13.0, "step": 0.5, "group": 'Ports', "label": 'Port bore diameter (mm)'},
    "hole_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<X').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('<X').workplane()
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>Y').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>Y').workplane()
        .hole(p["port_bore"])
    )
    result = (
        result.faces('<Y').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('<Y').workplane()
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>X').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>X').workplane()
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.08120310956471985)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
