import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004385 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 74.43, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 83.6, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 57.5, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_a": {"type": 'float', "default": 15.3, "min": 7.7, "max": 40.2, "step": 1.0, "group": 'Spigot', "label": 'Spigot width (mm)'},
    "spig_b": {"type": 'float', "default": 8.6, "min": 4.3, "max": 40.2, "step": 1.0, "group": 'Spigot', "label": 'Spigot depth (mm)'},
    "spig_len": {"type": 'float', "default": 9.6, "min": 2.6, "max": 34.4, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
    "spig_bore": {"type": 'float', "default": 4.9, "min": 2.0, "max": 6.2, "step": 0.5, "group": 'Spigot', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .rect(p["spig_a"], p["spig_b"]).extrude(p["spig_len"])
    )
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .hole(p["spig_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
