import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004062 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_w": {"type": 'float', "default": 80, "min": 30.0, "max": 160.0, "step": 1.0, "group": 'Base', "label": 'Base width (mm)'},
    "base_d": {"type": 'float', "default": 65.8, "min": 25.0, "max": 160.0, "step": 1.0, "group": 'Base', "label": 'Base depth (mm)'},
    "base_h": {"type": 'float', "default": 20.0, "min": 3.0, "max": 30.0, "step": 0.5, "group": 'Base', "label": 'Base thickness (mm)'},
    "col_d": {"type": 'float', "default": 22.6, "min": 9.0, "max": 32.9, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 46.8, "min": 14.0, "max": 140.4, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
    "hole_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["base_w"], p["base_d"], p["base_h"])
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["base_w"] * 0.7, p["base_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
