import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004623 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 56.22, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body width (mm)'},
    "block_d": {"type": 'float', "default": 45.2, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body depth (mm)'},
    "block_h": {"type": 'float', "default": 30.1, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body height (mm)'},
    "port_d": {"type": 'float', "default": 9.9, "min": 4.0, "max": 13.5, "step": 1.0, "group": 'Ports', "label": 'Ports diameter (mm)'},
    "port_len": {"type": 'float', "default": 10.4, "min": 2.5, "max": 29.7, "step": 1.0, "group": 'Ports', "label": 'Port boss length (mm)'},
    "port_bore": {"type": 'float', "default": 5.3, "min": 2.0, "max": 7.1, "step": 0.5, "group": 'Ports', "label": 'Port bore diameter (mm)'},
    "hole_d": {"type": 'float', "default": 8.4, "min": 2.0, "max": 10.2, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<X').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('<X').workplane()
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>Y').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>Y').workplane()
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>X').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>X').workplane()
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
