import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004262 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 31.04, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 24.2, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 24.4, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_d": {"type": 'float', "default": 10.2, "min": 4.1, "max": 17.1, "step": 1.0, "group": 'Spigot', "label": 'Spigot diameter (mm)'},
    "spig_len": {"type": 'float', "default": 22.7, "min": 3.1, "max": 40.8, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
    "hole_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 5.4, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Y').workplane(centerOption='CenterOfBoundBox')
        .circle(p["spig_d"] / 2).extrude(p["spig_len"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
