import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004446 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 70, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 66.7, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 44.5, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_d": {"type": 'float', "default": 21.2, "min": 8.5, "max": 31.1, "step": 1.0, "group": 'Spigot', "label": 'Spigot diameter (mm)'},
    "spig_len": {"type": 'float', "default": 52.8, "min": 6.4, "max": 84.8, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
    "hole_d": {"type": 'float', "default": 6.4, "min": 2.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<X').workplane(centerOption='CenterOfBoundBox')
        .circle(p["spig_d"] / 2).extrude(p["spig_len"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
