import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004672 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "shaft_d": {"type": 'float', "default": 35.14, "min": 17.6, "max": 63.3, "step": 1.0, "group": 'Body', "label": 'Shaft diameter (mm)'},
    "shaft_len": {"type": 'float', "default": 44.2, "min": 17.7, "max": 88.4, "step": 1.0, "group": 'Body', "label": 'Shaft length (mm)'},
    "step_d": {"type": 'float', "default": 17.7, "min": 8.8, "max": 31.6, "step": 1.0, "group": 'Step', "label": 'Step diameter (mm)'},
    "step_len": {"type": 'float', "default": 29.8, "min": 8.9, "max": 74.5, "step": 1.0, "group": 'Step', "label": 'Step length (mm)'},
    "chamfer_d": {"type": 'float', "default": 2.9, "min": 0.5, "max": 3.0, "step": 0.5, "group": 'Body', "label": 'Chamfer distance (mm)'},
    "chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'Chamfer edges'},
}


def build(p):

    result = (cq.Workplane('XY').circle(p["shaft_d"] / 2).extrude(p["shaft_len"]))
    result = (
        result.faces('>Z').workplane()
        .circle(p["step_d"] / 2).extrude(p["step_len"])
    )
    if p["chamfered"]:
        result = result.edges('<Z').chamfer(p["chamfer_d"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
