import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004166 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "shaft_d": {"type": 'float', "default": 41.62, "min": 20.8, "max": 74.9, "step": 1.0, "group": 'Body', "label": 'Shaft diameter (mm)'},
    "shaft_len": {"type": 'float', "default": 48.1, "min": 19.2, "max": 96.2, "step": 1.0, "group": 'Body', "label": 'Shaft length (mm)'},
    "step_d": {"type": 'float', "default": 24.9, "min": 12.4, "max": 37.5, "step": 1.0, "group": 'Step', "label": 'Step diameter (mm)'},
    "step_len": {"type": 'float', "default": 30.4, "min": 9.1, "max": 76.0, "step": 1.0, "group": 'Step', "label": 'Step length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').circle(p["shaft_d"] / 2).extrude(p["shaft_len"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["step_d"] / 2).extrude(p["step_len"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
