import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004086 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_sides": {"type": 'int', "default": 5, "min": 3, "max": 8, "step": 1, "group": 'Base', "label": 'Base sides'},
    "base_r": {"type": 'float', "default": 15.5, "min": 9.3, "max": 24.8, "step": 1.0, "group": 'Base', "label": 'Base circumradius (mm)'},
    "base_h": {"type": 'float', "default": 8.1, "min": 3.2, "max": 20.2, "step": 1.0, "group": 'Base', "label": 'Base height (mm)'},
    "col_d": {"type": 'float', "default": 14.4, "min": 7.2, "max": 20.1, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 15.7, "min": 4.7, "max": 39.2, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
    "col_bore": {"type": 'float', "default": 6.7, "min": 2.0, "max": 10.4, "step": 0.5, "group": 'Column', "label": 'Column bore diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["base_sides"], p["base_r"] * 2).extrude(p["base_h"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["col_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
