import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004199 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "adapter_base": {"type": 'float', "default": 60, "min": 36.0, "max": 90.0, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "adapter_top": {"type": 'float', "default": 32.5, "min": 16.2, "max": 60, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "adapter_h": {"type": 'float', "default": 42.8, "min": 17.1, "max": 85.6, "step": 1.0, "group": 'Body', "label": 'Transition height (mm)'},
    "neck_d": {"type": 'float', "default": 20.2, "min": 8.1, "max": 32.5, "step": 1.0, "group": 'Neck', "label": 'Neck diameter (mm)'},
    "neck_l": {"type": 'float', "default": 29.2, "min": 11.7, "max": 73.0, "step": 1.0, "group": 'Neck', "label": 'Neck length (mm)'},
    "neck_bore": {"type": 'float', "default": 12.0, "min": 2.0, "max": 14.5, "step": 0.5, "group": 'Neck', "label": 'Neck bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .circle(p["adapter_base"] / 2)
        .workplane(offset=p["adapter_h"])
        .rect(p["adapter_top"], p["adapter_top"])
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["neck_d"] / 2).extrude(p["neck_l"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["neck_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
