import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234003908 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 45, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body width (mm)'},
    "block_d": {"type": 'float', "default": 44.9, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body depth (mm)'},
    "block_h": {"type": 'float', "default": 42.5, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body height (mm)'},
    "port_d": {"type": 'float', "default": 9.3, "min": 3.7, "max": 19.1, "step": 1.0, "group": 'Ports', "label": 'Ports diameter (mm)'},
    "port_len": {"type": 'float', "default": 6.3, "min": 2.3, "max": 27.9, "step": 1.0, "group": 'Ports', "label": 'Port boss length (mm)'},
    "port_bore": {"type": 'float', "default": 3.8, "min": 2.0, "max": 6.7, "step": 0.5, "group": 'Ports', "label": 'Port bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<Y').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('<Y').workplane()
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>Y').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>Y').workplane()
        .hole(p["port_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
