import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004328 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 67.11, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 85.3, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 67.2, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_w": {"type": 'float', "default": 19.7, "min": 9.8, "max": 37.6, "step": 0.5, "group": 'Spigot', "label": 'Spigot width (mm)'},
    "spig_slot_l": {"type": 'float', "default": 36.7, "min": 23.6, "max": 47.0, "step": 1.0, "group": 'Spigot', "label": 'Spigot slot length (mm)'},
    "spig_len": {"type": 'float', "default": 20.8, "min": 5.9, "max": 78.8, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .slot2D(p["spig_slot_l"], p["spig_w"]).extrude(p["spig_len"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
