import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004134 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "shaft_d": {"type": 'float', "default": 15.22, "min": 7.6, "max": 27.4, "step": 1.0, "group": 'Body', "label": 'Shaft diameter (mm)'},
    "shaft_len": {"type": 'float', "default": 26.5, "min": 10.6, "max": 53.0, "step": 1.0, "group": 'Body', "label": 'Shaft length (mm)'},
    "step_d": {"type": 'float', "default": 8.4, "min": 4.2, "max": 13.7, "step": 1.0, "group": 'Step', "label": 'Step diameter (mm)'},
    "step_len": {"type": 'float', "default": 10.9, "min": 3.3, "max": 27.2, "step": 1.0, "group": 'Step', "label": 'Step length (mm)'},
    "axial_bore": {"type": 'float', "default": 3.6, "min": 2.0, "max": 6.0, "step": 0.5, "group": 'Bore', "label": 'Axial bore diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').circle(p["shaft_d"] / 2).extrude(p["shaft_len"]))
    result = (
        result.faces('>Z').workplane()
        .circle(p["step_d"] / 2).extrude(p["step_len"])
    )
    result = (
        result.faces('>Z').workplane()
        .hole(p["axial_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
