import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004024 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 24.36, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 20.1, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 25.4, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_d": {"type": 'float', "default": 10.1, "min": 4.0, "max": 17.1, "step": 1.0, "group": 'Spigot', "label": 'Spigot diameter (mm)'},
    "spig_len": {"type": 'float', "default": 17.2, "min": 3.0, "max": 40.4, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
    "spig_bore": {"type": 'float', "default": 4.5, "min": 2.0, "max": 7.3, "step": 0.5, "group": 'Spigot', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<Y').workplane()
        .circle(p["spig_d"] / 2).extrude(p["spig_len"])
    )
    result = (
        result.faces('<Y').workplane()
        .hole(p["spig_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
