import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004603 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "adapter_base": {"type": 'float', "default": 64.09, "min": 38.5, "max": 96.1, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "adapter_top": {"type": 'float', "default": 27.0, "min": 13.5, "max": 64.1, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "adapter_h": {"type": 'float', "default": 67.7, "min": 27.1, "max": 135.4, "step": 1.0, "group": 'Body', "label": 'Transition height (mm)'},
    "neck_d": {"type": 'float', "default": 18.9, "min": 7.6, "max": 27.0, "step": 1.0, "group": 'Neck', "label": 'Neck diameter (mm)'},
    "neck_l": {"type": 'float', "default": 15.8, "min": 6.3, "max": 39.5, "step": 1.0, "group": 'Neck', "label": 'Neck length (mm)'},
    "neck_bore": {"type": 'float', "default": 11.0, "min": 2.0, "max": 13.6, "step": 0.5, "group": 'Neck', "label": 'Neck bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .circle(p["adapter_base"] / 2)
        .workplane(offset=p["adapter_h"])
        .rect(p["adapter_top"], p["adapter_top"])
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["neck_d"] / 2).extrude(p["neck_l"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["neck_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
