import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004138 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_sides": {"type": 'int', "default": 5, "min": 3, "max": 8, "step": 1, "group": 'Base', "label": 'Base sides'},
    "base_r": {"type": 'float', "default": 27.08, "min": 16.2, "max": 43.3, "step": 1.0, "group": 'Base', "label": 'Base circumradius (mm)'},
    "base_h": {"type": 'float', "default": 27.8, "min": 11.1, "max": 69.5, "step": 1.0, "group": 'Base', "label": 'Base height (mm)'},
    "col_d": {"type": 'float', "default": 25.3, "min": 12.7, "max": 35.1, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 29.2, "min": 8.8, "max": 73.0, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
    "col_bore": {"type": 'float', "default": 10.3, "min": 2.0, "max": 18.2, "step": 0.5, "group": 'Column', "label": 'Column bore diameter (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["base_sides"], p["base_r"] * 2).extrude(p["base_h"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["col_bore"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["base_r"], p["base_r"]) * 0.08497391791024642)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
