import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234003940 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 40, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body width (mm)'},
    "block_d": {"type": 'float', "default": 29.1, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body depth (mm)'},
    "block_h": {"type": 'float', "default": 21.1, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body height (mm)'},
    "port_sides": {"type": 'int', "default": 8, "min": 3, "max": 8, "step": 1, "group": 'Ports', "label": 'Ports sides'},
    "port_r": {"type": 'float', "default": 3.0, "min": 1.5, "max": 4.8, "step": 1.0, "group": 'Ports', "label": 'Ports circumradius (mm)'},
    "port_len": {"type": 'float', "default": 4.0, "min": 1.4, "max": 16.6, "step": 1.0, "group": 'Ports', "label": 'Port boss length (mm)'},
    "hole_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 6.5, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<Y').workplane(centerOption='CenterOfBoundBox')
        .polygon(p["port_sides"], p["port_r"] * 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>X').workplane(centerOption='CenterOfBoundBox')
        .polygon(p["port_sides"], p["port_r"] * 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>Y').workplane(centerOption='CenterOfBoundBox')
        .polygon(p["port_sides"], p["port_r"] * 2).extrude(p["port_len"])
    )
    result = (
        result.faces('<X').workplane(centerOption='CenterOfBoundBox')
        .polygon(p["port_sides"], p["port_r"] * 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.06835382212618568)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
