import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004143 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_w": {"type": 'float', "default": 45.28, "min": 30.0, "max": 160.0, "step": 1.0, "group": 'Base', "label": 'Base width (mm)'},
    "base_d": {"type": 'float', "default": 38.8, "min": 25.0, "max": 160.0, "step": 1.0, "group": 'Base', "label": 'Base depth (mm)'},
    "base_h": {"type": 'float', "default": 10.0, "min": 3.0, "max": 30.0, "step": 0.5, "group": 'Base', "label": 'Base thickness (mm)'},
    "col_sides": {"type": 'int', "default": 5, "min": 3, "max": 8, "step": 1, "group": 'Column', "label": 'Column sides'},
    "col_r": {"type": 'float', "default": 6.7, "min": 3.4, "max": 9.7, "step": 1.0, "group": 'Column', "label": 'Column circumradius (mm)'},
    "col_h": {"type": 'float', "default": 32.0, "min": 9.6, "max": 96.0, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
    "col_bore": {"type": 'float', "default": 6.7, "min": 2.0, "max": 7.8, "step": 0.5, "group": 'Column', "label": 'Column bore diameter (mm)'},
    "hole_d": {"type": 'float', "default": 8.4, "min": 2.0, "max": 8.7, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["base_w"], p["base_d"], p["base_h"])
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .polygon(p["col_sides"], p["col_r"] * 2).extrude(p["col_h"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["col_bore"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["base_w"] * 0.7, p["base_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
