import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004288 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 34.66, "min": 15.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block width (mm)'},
    "block_d": {"type": 'float', "default": 42.1, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block depth (mm)'},
    "block_h": {"type": 'float', "default": 37.2, "min": 10.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Block height (mm)'},
    "spig_d": {"type": 'float', "default": 8.9, "min": 3.6, "max": 24.3, "step": 1.0, "group": 'Spigot', "label": 'Spigot diameter (mm)'},
    "spig_len": {"type": 'float', "default": 21.2, "min": 2.7, "max": 35.6, "step": 1.0, "group": 'Spigot', "label": 'Spigot length (mm)'},
    "spig_bore": {"type": 'float', "default": 3.9, "min": 2.0, "max": 6.4, "step": 0.5, "group": 'Spigot', "label": 'Bore diameter (mm)'},
    "hole_d": {"type": 'float', "default": 5.3, "min": 2.0, "max": 7.8, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Y').workplane(centerOption='CenterOfBoundBox')
        .circle(p["spig_d"] / 2).extrude(p["spig_len"])
    )
    result = (
        result.faces('>Y').workplane(centerOption='CenterOfBoundBox')
        .hole(p["spig_bore"])
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["block_w"] * 0.7, p["block_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["block_w"], p["block_d"]) * 0.11089002544897664)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
