import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004470 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 37.17, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body width (mm)'},
    "block_d": {"type": 'float', "default": 37.9, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body depth (mm)'},
    "block_h": {"type": 'float', "default": 35.5, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body height (mm)'},
    "port_d": {"type": 'float', "default": 8.7, "min": 3.5, "max": 16.0, "step": 1.0, "group": 'Ports', "label": 'Ports diameter (mm)'},
    "port_len": {"type": 'float', "default": 10.6, "min": 2.2, "max": 26.1, "step": 1.0, "group": 'Ports', "label": 'Port boss length (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('>Y').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>X').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
