import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004101 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_sides": {"type": 'int', "default": 6, "min": 3, "max": 8, "step": 1, "group": 'Base', "label": 'Base sides'},
    "base_r": {"type": 'float', "default": 25, "min": 15.0, "max": 40.0, "step": 1.0, "group": 'Base', "label": 'Base circumradius (mm)'},
    "base_h": {"type": 'float', "default": 20.0, "min": 8.0, "max": 50.0, "step": 1.0, "group": 'Base', "label": 'Base height (mm)'},
    "col_d": {"type": 'float', "default": 22.8, "min": 11.4, "max": 34.6, "step": 1.0, "group": 'Column', "label": 'Column diameter (mm)'},
    "col_h": {"type": 'float', "default": 24.0, "min": 7.2, "max": 60.0, "step": 1.0, "group": 'Column', "label": 'Column height (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["base_sides"], p["base_r"] * 2).extrude(p["base_h"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["col_d"] / 2).extrude(p["col_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
