import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004131 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "shaft_d": {"type": 'float', "default": 12.71, "min": 6.4, "max": 22.9, "step": 1.0, "group": 'Body', "label": 'Shaft diameter (mm)'},
    "shaft_len": {"type": 'float', "default": 21.9, "min": 8.8, "max": 43.8, "step": 1.0, "group": 'Body', "label": 'Shaft length (mm)'},
    "step_d": {"type": 'float', "default": 6.1, "min": 3.0, "max": 11.4, "step": 1.0, "group": 'Step', "label": 'Step diameter (mm)'},
    "step_len": {"type": 'float', "default": 9.6, "min": 2.9, "max": 24.0, "step": 1.0, "group": 'Step', "label": 'Step length (mm)'},
    "axial_bore": {"type": 'float', "default": 2.5, "min": 2.0, "max": 4.4, "step": 0.5, "group": 'Bore', "label": 'Axial bore diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').circle(p["shaft_d"] / 2).extrude(p["shaft_len"]))
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .circle(p["step_d"] / 2).extrude(p["step_len"])
    )
    result = (
        result.faces('>Z').workplane(centerOption='CenterOfBoundBox')
        .hole(p["axial_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
