import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004102 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "block_w": {"type": 'float', "default": 54.12, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body width (mm)'},
    "block_d": {"type": 'float', "default": 37.1, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body depth (mm)'},
    "block_h": {"type": 'float', "default": 43.1, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Body height (mm)'},
    "port_d": {"type": 'float', "default": 12.3, "min": 4.9, "max": 16.7, "step": 1.0, "group": 'Ports', "label": 'Ports diameter (mm)'},
    "port_len": {"type": 'float', "default": 11.9, "min": 3.1, "max": 36.9, "step": 1.0, "group": 'Ports', "label": 'Port boss length (mm)'},
    "port_bore": {"type": 'float', "default": 5.9, "min": 2.0, "max": 8.9, "step": 0.5, "group": 'Ports', "label": 'Port bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["block_w"], p["block_d"], p["block_h"])
    result = (
        result.faces('<Y').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('<Y').workplane()
        .hole(p["port_bore"])
    )
    result = (
        result.faces('>Y').workplane()
        .circle(p["port_d"] / 2).extrude(p["port_len"])
    )
    result = (
        result.faces('>Y').workplane()
        .hole(p["port_bore"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
