import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234003816 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "enc_w": {"type": 'float', "default": 80, "min": 30.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Enclosure width (mm)'},
    "enc_d": {"type": 'float', "default": 35.4, "min": 12.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Enclosure depth (mm)'},
    "enc_h": {"type": 'float', "default": 43.3, "min": 17.3, "max": 86.6, "step": 1.0, "group": 'Body', "label": 'Enclosure height (mm)'},
    "wall_t": {"type": 'float', "default": 2.5, "min": 2.0, "max": 6.0, "step": 0.5, "group": 'Body', "label": 'Wall thickness (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["enc_w"], p["enc_d"], p["enc_h"])
    result = result.faces('>Z').shell(-p["wall_t"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
