import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004242 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "enc_w": {"type": 'float', "default": 115, "min": 30.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Enclosure width (mm)'},
    "enc_d": {"type": 'float', "default": 64.8, "min": 12.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Enclosure depth (mm)'},
    "enc_h": {"type": 'float', "default": 67.0, "min": 26.8, "max": 134.0, "step": 1.0, "group": 'Body', "label": 'Enclosure height (mm)'},
    "wall_t": {"type": 'float', "default": 5.1, "min": 2.0, "max": 6.0, "step": 0.5, "group": 'Body', "label": 'Wall thickness (mm)'},
    "hole_d": {"type": 'float', "default": 13.0, "min": 2.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = cq.Workplane('XY').box(p["enc_w"], p["enc_d"], p["enc_h"])
    result = result.faces('>Z').shell(-p["wall_t"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["enc_w"] * 0.7, p["enc_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["enc_w"], p["enc_d"]) * 0.05521644091161011)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
