import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003758 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "enc_w": {"type": 'float', "default": 38.02, "min": 30.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Enclosure width (mm)'},
    "enc_d": {"type": 'float', "default": 27.9, "min": 12.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Enclosure depth (mm)'},
    "enc_h": {"type": 'float', "default": 29.2, "min": 11.7, "max": 58.4, "step": 1.0, "group": 'Body', "label": 'Enclosure height (mm)'},
    "wall_t": {"type": 'float', "default": 3.1, "min": 2.0, "max": 6.0, "step": 0.5, "group": 'Body', "label": 'Wall thickness (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["enc_w"], p["enc_d"], p["enc_h"])
    result = result.faces('>Z').shell(-p["wall_t"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
