import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004506 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "enc_w": {"type": 'float', "default": 106.22, "min": 30.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Enclosure width (mm)'},
    "enc_d": {"type": 'float', "default": 43.2, "min": 12.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Enclosure depth (mm)'},
    "enc_h": {"type": 'float', "default": 69.3, "min": 27.7, "max": 138.6, "step": 1.0, "group": 'Body', "label": 'Enclosure height (mm)'},
    "wall_t": {"type": 'float', "default": 3.4, "min": 2.0, "max": 6.0, "step": 0.5, "group": 'Body', "label": 'Wall thickness (mm)'},
    "hole_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 9.7, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = cq.Workplane('XY').box(p["enc_w"], p["enc_d"], p["enc_h"])
    result = result.faces('>Z').shell(-p["wall_t"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["enc_w"] * 0.7, p["enc_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["enc_w"], p["enc_d"]) * 0.04144931727539882)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
