import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234003847 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 64.5, "min": 20.0, "max": 100.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 78.7, "min": 23.6, "max": 196.8, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "inner_d": {"type": 'float', "default": 25.7, "min": 2.0, "max": 45.1, "step": 0.5, "group": 'Body', "label": 'Bore diameter (mm)'},
    "flange_d": {"type": 'float', "default": 153.8, "min": 83.9, "max": 193.5, "step": 1.0, "group": 'Flange', "label": 'Flange diameter (mm)'},
    "flange_h": {"type": 'float', "default": 9.0, "min": 2.7, "max": 31.5, "step": 0.5, "group": 'Flange', "label": 'Flange height (mm)'},
    "bolt_d": {"type": 'float', "default": 8.4, "min": 3.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Bolt hole diameter (mm)'},
    "bolt_r": {"type": 'float', "default": 46.1, "min": 30.8, "max": 69.2, "step": 1.0, "group": 'Holes', "label": 'Bolt circle radius (mm)'},
    "n_bolts": {"type": 'int', "default": 6, "min": 3, "max": 12, "step": 1, "group": 'Holes', "label": 'Number of bolts'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(p["inner_d"] / 2, 0)
        .lineTo(p["flange_d"] / 2, 0)
        .lineTo(p["flange_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["length"])
        .lineTo(p["inner_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    result = (
        result.faces('>Z').workplane()
        .polarArray(p["bolt_r"], 0, 360, p["n_bolts"])
        .hole(p["bolt_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
