import cadquery as cq
import math
import py_gearworks as _gw

# Generated by CadQuarry v0.6.0 — seed 1234004242 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "module": {"type": 'float', "default": 3.0, "min": 1.0, "max": 6.0, "step": 0.25, "group": 'Gear', "label": 'Module (mm)'},
    "teeth": {"type": 'int', "default": 26, "min": 10, "max": 40, "step": 1, "group": 'Gear', "label": 'Number of teeth'},
    "gear_w": {"type": 'float', "default": 17.8, "min": 7.1, "max": 44.5, "step": 1.0, "group": 'Gear', "label": 'Face width (mm)'},
    "profile_shift": {"type": 'float', "default": 0.25, "min": -0.5, "max": 0.7, "step": 0.05, "group": 'Gear', "label": 'Profile shift'},
    "root_fillet": {"type": 'float', "default": 0.45, "min": 0.0, "max": 1.5, "step": 0.05, "group": 'Gear', "label": 'Root fillet (mm)'},
    "bore_d": {"type": 'float', "default": 11.9, "min": 2.0, "max": 42.3, "step": 0.5, "group": 'Bore', "label": 'Bore diameter (mm)'},
    "hub_d": {"type": 'float', "default": 21.4, "min": 16.7, "max": 39.0, "step": 1.0, "group": 'Hub', "label": 'Hub diameter (mm)'},
    "hub_h": {"type": 'float', "default": 10.5, "min": 3.1, "max": 21.0, "step": 0.5, "group": 'Hub', "label": 'Hub height (mm)'},
}


def build(p):

    _gear = _gw.SpurGear(number_of_teeth=int(p["teeth"]), height=p["gear_w"], module=p["module"], profile_shift=p["profile_shift"], root_fillet=p["root_fillet"])
    _gpart = _gear.build_part()
    result = cq.Workplane('XY').add(cq.Solid(_gpart.wrapped))
    result = (
        result.faces('>Z').workplane()
        .circle(p["hub_d"] / 2).extrude(p["hub_h"])
    )
    result = result.faces('>Z').workplane().hole(p["bore_d"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
