import cadquery as cq
import math
import py_gearworks as _gw

# Generated by CadQuarry v0.6.0 — seed 1234004026 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "module": {"type": 'float', "default": 2.5, "min": 1.0, "max": 6.0, "step": 0.25, "group": 'Gear', "label": 'Module (mm)'},
    "teeth": {"type": 'int', "default": 26, "min": 10, "max": 40, "step": 1, "group": 'Gear', "label": 'Number of teeth'},
    "gear_w": {"type": 'float', "default": 13.4, "min": 5.4, "max": 33.5, "step": 1.0, "group": 'Gear', "label": 'Face width (mm)'},
    "bore_d": {"type": 'float', "default": 13.2, "min": 2.0, "max": 35.2, "step": 0.5, "group": 'Bore', "label": 'Bore diameter (mm)'},
}


def build(p):

    _gear = _gw.SpurGear(number_of_teeth=int(p["teeth"]), height=p["gear_w"], module=p["module"])
    _gpart = _gear.build_part()
    result = cq.Workplane('XY').add(cq.Solid(_gpart.wrapped))
    result = result.faces('>Z').workplane().hole(p["bore_d"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
