import cadquery as cq
import math
import py_gearworks as _gw

# Generated by CadQuarry v0.5.0 — seed 1234004135 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "module": {"type": 'float', "default": 1.5, "min": 1.0, "max": 6.0, "step": 0.25, "group": 'Gear', "label": 'Module (mm)'},
    "teeth": {"type": 'int', "default": 19, "min": 10, "max": 40, "step": 1, "group": 'Gear', "label": 'Number of teeth'},
    "gear_w": {"type": 'float', "default": 9.9, "min": 4.0, "max": 24.8, "step": 1.0, "group": 'Gear', "label": 'Face width (mm)'},
    "profile_shift": {"type": 'float', "default": 0.37, "min": -0.5, "max": 0.7, "step": 0.05, "group": 'Gear', "label": 'Profile shift'},
    "root_fillet": {"type": 'float', "default": 0.4, "min": 0.0, "max": 0.75, "step": 0.05, "group": 'Gear', "label": 'Root fillet (mm)'},
    "bore_d": {"type": 'float', "default": 5.5, "min": 2.0, "max": 14.8, "step": 0.5, "group": 'Bore', "label": 'Bore diameter (mm)'},
}


def build(p):

    _gear = _gw.SpurGear(number_of_teeth=int(p["teeth"]), height=p["gear_w"], module=p["module"], profile_shift=p["profile_shift"], root_fillet=p["root_fillet"])
    _gpart = _gear.build_part()
    result = cq.Workplane('XY').add(cq.Solid(_gpart.wrapped))
    result = result.faces('>Z').workplane().hole(p["bore_d"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
