import cadquery as cq
import math
import py_gearworks as _gw

# Generated by CadQuarry v0.5.0 — seed 1234004740 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "module": {"type": 'float', "default": 6.0, "min": 1.0, "max": 6.0, "step": 0.25, "group": 'Gear', "label": 'Module (mm)'},
    "teeth": {"type": 'int', "default": 34, "min": 10, "max": 40, "step": 1, "group": 'Gear', "label": 'Number of teeth'},
    "gear_w": {"type": 'float', "default": 34.0, "min": 13.6, "max": 85.0, "step": 1.0, "group": 'Gear', "label": 'Face width (mm)'},
    "bore_d": {"type": 'float', "default": 30.3, "min": 2.0, "max": 113.4, "step": 0.5, "group": 'Bore', "label": 'Bore diameter (mm)'},
}


def build(p):

    _gear = _gw.SpurGear(number_of_teeth=int(p["teeth"]), height=p["gear_w"], module=p["module"])
    _gpart = _gear.build_part()
    result = cq.Workplane('XY').add(cq.Solid(_gpart.wrapped))
    result = result.faces('>Z').workplane().hole(p["bore_d"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
