import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003874 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "loft_base": {"type": 'float', "default": 45, "min": 22.5, "max": 72.0, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "loft_top": {"type": 'float', "default": 28.9, "min": 11.6, "max": 54.0, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "loft_h": {"type": 'float', "default": 28.2, "min": 11.3, "max": 56.4, "step": 1.0, "group": 'Body', "label": 'Height (mm)'},
    "loft_mid": {"type": 'float', "default": 37.0, "min": 14.4, "max": 54.0, "step": 1.0, "group": 'Body', "label": 'Mid size (mm)'},
    "loft_bore_d": {"type": 'float', "default": 14.0, "min": 2.0, "max": 23.1, "step": 0.5, "group": 'Holes', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .polygon(6, p["loft_base"] * 0.5 * 2)
        .workplane(offset=p["loft_h"] * 0.5)
        .circle(p["loft_mid"] / 2)
        .workplane(offset=p["loft_h"] * 0.5)
        .rect(p["loft_top"], p["loft_top"])
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["loft_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
