import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003838 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "loft_base": {"type": 'float', "default": 60, "min": 30.0, "max": 96.0, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "loft_top": {"type": 'float', "default": 21.6, "min": 8.6, "max": 72.0, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "loft_h": {"type": 'float', "default": 71.5, "min": 28.6, "max": 143.0, "step": 1.0, "group": 'Body', "label": 'Height (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .rect(p["loft_base"], p["loft_base"])
        .workplane(offset=p["loft_h"])
        .circle(p["loft_top"] / 2)
        .loft(combine=True)
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
