import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004331 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "loft_base": {"type": 'float', "default": 62.92, "min": 31.5, "max": 100.7, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "loft_top": {"type": 'float', "default": 49.1, "min": 19.6, "max": 75.5, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "loft_h": {"type": 'float', "default": 48.0, "min": 19.2, "max": 96.0, "step": 1.0, "group": 'Body', "label": 'Height (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .circle(p["loft_base"] / 2)
        .workplane(offset=p["loft_h"])
        .rect(p["loft_top"], p["loft_top"])
        .loft(combine=True)
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
