import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004417 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "loft_base": {"type": 'float', "default": 60, "min": 30.0, "max": 96.0, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "loft_top": {"type": 'float', "default": 27.4, "min": 11.0, "max": 72.0, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "loft_h": {"type": 'float', "default": 54.0, "min": 21.6, "max": 108.0, "step": 1.0, "group": 'Body', "label": 'Height (mm)'},
    "loft_mid": {"type": 'float', "default": 43.7, "min": 13.7, "max": 72.0, "step": 1.0, "group": 'Body', "label": 'Mid size (mm)'},
    "loft_bore_d": {"type": 'float', "default": 13.5, "min": 2.0, "max": 21.9, "step": 0.5, "group": 'Holes', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .rect(p["loft_base"], p["loft_base"])
        .workplane(offset=p["loft_h"] * 0.5)
        .rect(p["loft_mid"], p["loft_mid"])
        .workplane(offset=p["loft_h"] * 0.5)
        .polygon(6, p["loft_top"] * 0.5 * 2)
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["loft_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
