import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004114 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "loft_base": {"type": 'float', "default": 46.52, "min": 23.3, "max": 74.4, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "loft_top": {"type": 'float', "default": 25.4, "min": 10.2, "max": 55.8, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "loft_h": {"type": 'float', "default": 23.9, "min": 9.6, "max": 47.8, "step": 1.0, "group": 'Body', "label": 'Height (mm)'},
    "loft_bore_d": {"type": 'float', "default": 9.9, "min": 2.0, "max": 20.3, "step": 0.5, "group": 'Holes', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .rect(p["loft_base"], p["loft_base"])
        .workplane(offset=p["loft_h"])
        .polygon(6, p["loft_top"] * 0.5 * 2)
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["loft_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
