import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004601 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "loft_base": {"type": 'float', "default": 50.25, "min": 25.1, "max": 80.4, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "loft_top": {"type": 'float', "default": 20.3, "min": 8.1, "max": 60.3, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "loft_h": {"type": 'float', "default": 65.0, "min": 26.0, "max": 130.0, "step": 1.0, "group": 'Body', "label": 'Height (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .polygon(6, p["loft_base"] * 0.5 * 2)
        .workplane(offset=p["loft_h"])
        .circle(p["loft_top"] / 2)
        .loft(combine=True)
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
