import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003956 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "loft_base": {"type": 'float', "default": 55, "min": 27.5, "max": 88.0, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "loft_top": {"type": 'float', "default": 17.5, "min": 7.0, "max": 66.0, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "loft_h": {"type": 'float', "default": 34.5, "min": 13.8, "max": 69.0, "step": 1.0, "group": 'Body', "label": 'Height (mm)'},
    "loft_bore_d": {"type": 'float', "default": 6.5, "min": 2.0, "max": 14.0, "step": 0.5, "group": 'Holes', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .rect(p["loft_base"], p["loft_base"])
        .workplane(offset=p["loft_h"])
        .circle(p["loft_top"] / 2)
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["loft_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
