import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004220 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "loft_base": {"type": 'float', "default": 34.25, "min": 17.1, "max": 54.8, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "loft_top": {"type": 'float', "default": 20.9, "min": 8.4, "max": 41.1, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "loft_h": {"type": 'float', "default": 28.2, "min": 11.3, "max": 56.4, "step": 1.0, "group": 'Body', "label": 'Height (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .circle(p["loft_base"] / 2)
        .workplane(offset=p["loft_h"])
        .polygon(6, p["loft_top"] * 0.5 * 2)
        .loft(combine=True)
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
