import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003811 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "loft_base": {"type": 'float', "default": 30.0, "min": 15.0, "max": 48.0, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "loft_top": {"type": 'float', "default": 11.3, "min": 4.5, "max": 36.0, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "loft_h": {"type": 'float', "default": 24.6, "min": 9.8, "max": 49.2, "step": 1.0, "group": 'Body', "label": 'Height (mm)'},
    "loft_bore_d": {"type": 'float', "default": 4.7, "min": 2.0, "max": 9.0, "step": 0.5, "group": 'Holes', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .circle(p["loft_base"] / 2)
        .workplane(offset=p["loft_h"])
        .polygon(6, p["loft_top"] * 0.5 * 2)
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["loft_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
