import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004074 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "loft_base": {"type": 'float', "default": 45, "min": 22.5, "max": 72.0, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "loft_top": {"type": 'float', "default": 33.6, "min": 13.4, "max": 54.0, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "loft_h": {"type": 'float', "default": 48.9, "min": 19.6, "max": 97.8, "step": 1.0, "group": 'Body', "label": 'Height (mm)'},
    "loft_mid": {"type": 'float', "default": 39.3, "min": 16.8, "max": 54.0, "step": 1.0, "group": 'Body', "label": 'Mid size (mm)'},
    "loft_bore_d": {"type": 'float', "default": 16.9, "min": 2.0, "max": 26.9, "step": 0.5, "group": 'Holes', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .circle(p["loft_base"] / 2)
        .workplane(offset=p["loft_h"] * 0.5)
        .circle(p["loft_mid"] / 2)
        .workplane(offset=p["loft_h"] * 0.5)
        .polygon(6, p["loft_top"] * 0.5 * 2)
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["loft_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
