import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004078 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "loft_base": {"type": 'float', "default": 70.0, "min": 35.0, "max": 112.0, "step": 1.0, "group": 'Body', "label": 'Base size (mm)'},
    "loft_top": {"type": 'float', "default": 46.6, "min": 18.6, "max": 84.0, "step": 1.0, "group": 'Body', "label": 'Top size (mm)'},
    "loft_h": {"type": 'float', "default": 84.2, "min": 33.7, "max": 168.4, "step": 1.0, "group": 'Body', "label": 'Height (mm)'},
    "loft_bore_d": {"type": 'float', "default": 20.9, "min": 2.0, "max": 37.3, "step": 0.5, "group": 'Holes', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XY')
        .circle(p["loft_base"] / 2)
        .workplane(offset=p["loft_h"])
        .rect(p["loft_top"], p["loft_top"])
        .loft(combine=True)
    )
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["loft_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
