import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004020 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 109.88, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 47.1, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 8.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "hole_d": {"type": 'float', "default": 8.4, "min": 2.0, "max": 10.6, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "chamfer_d": {"type": 'float', "default": 1.4, "min": 1.3, "max": 2.1, "step": 0.5, "group": 'Body', "label": 'Chamfer distance (mm)'},
    "chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'Chamfer edges'},
    "pocket_w": {"type": 'float', "default": 65.8, "min": 32.9, "max": 87.9, "step": 1.0, "group": 'Pocket', "label": 'Pocket width (mm)'},
    "pocket_d": {"type": 'float', "default": 31.9, "min": 15.9, "max": 37.7, "step": 1.0, "group": 'Pocket', "label": 'Pocket depth (mm)'},
    "pocket_h": {"type": 'float', "default": 4.7, "min": 1.9, "max": 6.8, "step": 0.5, "group": 'Pocket', "label": 'Pocket height (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["plate_w"] * 0.7, p["plate_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    if p["chamfered"]:
        result = result.edges('|Z').chamfer(p["chamfer_d"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["pocket_w"], p["pocket_d"])
        .cutBlind(-p["pocket_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
