import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234004364 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 90.09, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 69.4, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 2.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "hole_d": {"type": 'float', "default": 8.4, "min": 2.0, "max": 13.0, "step": 0.5, "group": 'Holes', "label": 'Slot width (mm)'},
    "hole_slot_len": {"type": 'float', "default": 17.4, "min": 12.6, "max": 20.8, "step": 0.5, "group": 'Holes', "label": 'Slot length (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["plate_w"] * 0.7, p["plate_d"] * 0.7, forConstruction=True)
        .vertices().slot2D(p["hole_slot_len"], p["hole_d"]).cutThruAll()
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["plate_w"], p["plate_d"]) * 0.09744234440292066)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
