import cadquery as cq

# Generated by CadQuarry v0.1.0 — seed 1234003711 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 100, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 45.1, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 10.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "hole_d": {"type": 'float', "default": 5.3, "min": 2.0, "max": 10.1, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "chamfer_d": {"type": 'float', "default": 1.2, "min": 0.5, "max": 3.0, "step": 0.5, "group": 'Body', "label": 'Chamfer distance (mm)'},
    "chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'Chamfer edges'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["plate_w"] * 0.7, p["plate_d"] * 0.7, forConstruction=True)
        .vertices().hole(p["hole_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["plate_w"], p["plate_d"]) * 0.08891024522718319)
    if p["chamfered"]:
        result = result.edges('>Z').chamfer(p["chamfer_d"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
