import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004313 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 104.38, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 44.5, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 8.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "hole_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 5.3, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "hole_nx": {"type": 'int', "default": 3, "min": 1, "max": 4, "step": 1, "group": 'Holes', "label": 'Holes across'},
    "hole_ny": {"type": 'int', "default": 2, "min": 1, "max": 4, "step": 1, "group": 'Holes', "label": 'Holes deep'},
    "hole_slot_len": {"type": 'float', "default": 8.1, "min": 6.4, "max": 24.9, "step": 0.5, "group": 'Holes', "label": 'Slot length (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .rarray(41.8, 35.6, p["hole_nx"], p["hole_ny"])
        .slot2D(p["hole_slot_len"], p["hole_d"]).cutThruAll()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
