import cadquery as cq

# Generated by CadQuarry v0.1.0 — seed 1234004608 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 70, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 59.8, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 4.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "bolt_d": {"type": 'float', "default": 5.3, "min": 3.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Bolt hole diameter (mm)'},
    "bolt_r": {"type": 'float', "default": 21.0, "min": 14.0, "max": 31.5, "step": 1.0, "group": 'Holes', "label": 'Bolt circle radius (mm)'},
    "n_bolts": {"type": 'int', "default": 6, "min": 3, "max": 12, "step": 1, "group": 'Holes', "label": 'Number of bolts'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "chamfer_d": {"type": 'float', "default": 1.7, "min": 0.5, "max": 3.0, "step": 0.5, "group": 'Body', "label": 'Chamfer distance (mm)'},
    "chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'Chamfer edges'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .polarArray(p["bolt_r"], 0, 360, p["n_bolts"])
        .hole(p["bolt_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["plate_w"], p["plate_d"]) * 0.10227033436676597)
    if p["chamfered"]:
        result = result.edges('>Z').chamfer(p["chamfer_d"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
