import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004012 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 103.25, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 80.2, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 8.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "hole_d": {"type": 'float', "default": 6.4, "min": 2.0, "max": 12.5, "step": 0.1, "group": 'Holes', "label": 'Square hole size (mm)'},
    "hole_nx": {"type": 'int', "default": 3, "min": 1, "max": 4, "step": 1, "group": 'Holes', "label": 'Holes across'},
    "hole_ny": {"type": 'int', "default": 4, "min": 1, "max": 4, "step": 1, "group": 'Holes', "label": 'Holes deep'},
    "chamfer_d": {"type": 'float', "default": 1.7, "min": 1.6, "max": 2.6, "step": 0.5, "group": 'Body', "label": 'Chamfer distance (mm)'},
    "chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'Chamfer edges'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .rarray(41.3, 21.4, p["hole_nx"], p["hole_ny"])
        .rect(p["hole_d"], p["hole_d"]).cutThruAll()
    )
    if p["chamfered"]:
        result = result.edges('|Z').chamfer(p["chamfer_d"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
