import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004632 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 65.04, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 34.6, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 5.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "hole_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 4.2, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "hole_nx": {"type": 'int', "default": 4, "min": 1, "max": 4, "step": 1, "group": 'Holes', "label": 'Holes across'},
    "hole_ny": {"type": 'int', "default": 3, "min": 1, "max": 4, "step": 1, "group": 'Holes', "label": 'Holes deep'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .rarray(17.3, 13.8, p["hole_nx"], p["hole_ny"])
        .hole(p["hole_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["plate_w"], p["plate_d"]) * 0.055001856297831365)
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
