import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004460 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 85, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 30.4, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 5.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "hole_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 3.6, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "hole_nx": {"type": 'int', "default": 2, "min": 1, "max": 4, "step": 1, "group": 'Holes', "label": 'Holes across'},
    "hole_ny": {"type": 'int', "default": 2, "min": 1, "max": 4, "step": 1, "group": 'Holes', "label": 'Holes deep'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .rarray(68.0, 24.3, p["hole_nx"], p["hole_ny"])
        .hole(p["hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
