import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004353 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 62.08, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 23.6, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 5.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "hole_d": {"type": 'float', "default": 5.3, "min": 2.0, "max": 5.3, "step": 0.5, "group": 'Holes', "label": 'Slot width (mm)'},
    "hole_slot_len": {"type": 'float', "default": 7.1, "min": 7.9, "max": 7.1, "step": 0.5, "group": 'Holes', "label": 'Slot length (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["plate_w"] * 0.7, p["plate_d"] * 0.7, forConstruction=True)
        .vertices().slot2D(p["hole_slot_len"], p["hole_d"]).cutThruAll()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
