import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004538 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 39.38, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 17.5, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 6.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "hole_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 3.9, "step": 0.5, "group": 'Holes', "label": 'Slot width (mm)'},
    "hole_slot_len": {"type": 'float', "default": 5.2, "min": 4.8, "max": 5.2, "step": 0.5, "group": 'Holes', "label": 'Slot length (mm)'},
    "pocket_w": {"type": 'float', "default": 21.0, "min": 10.5, "max": 31.5, "step": 1.0, "group": 'Pocket', "label": 'Pocket width (mm)'},
    "pocket_d": {"type": 'float', "default": 9.3, "min": 4.7, "max": 14.0, "step": 1.0, "group": 'Pocket', "label": 'Pocket depth (mm)'},
    "pocket_h": {"type": 'float', "default": 3.4, "min": 1.4, "max": 5.1, "step": 0.5, "group": 'Pocket', "label": 'Pocket height (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .rect(p["plate_w"] * 0.7, p["plate_d"] * 0.7, forConstruction=True)
        .vertices().slot2D(p["hole_slot_len"], p["hole_d"]).cutThruAll()
    )
    result = (
        result.faces('>Z').workplane()
        .rect(p["pocket_w"], p["pocket_d"])
        .cutBlind(-p["pocket_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
