import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234003892 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 95, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 38.4, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 6.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "bolt_d": {"type": 'float', "default": 8.4, "min": 3.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Bolt hole diameter (mm)'},
    "bolt_r": {"type": 'float', "default": 28.5, "min": 19.0, "max": 42.8, "step": 1.0, "group": 'Holes', "label": 'Bolt circle radius (mm)'},
    "n_bolts": {"type": 'int', "default": 6, "min": 3, "max": 12, "step": 1, "group": 'Holes', "label": 'Number of bolts'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "boss_d": {"type": 'float', "default": 13.6, "min": 6.8, "max": 27.2, "step": 1.0, "group": 'Boss', "label": 'Boss diameter (mm)'},
    "boss_h": {"type": 'float', "default": 5.0, "min": 2.0, "max": 12.5, "step": 1.0, "group": 'Boss', "label": 'Boss height (mm)'},
    "boss_bore_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 9.5, "step": 0.1, "group": 'Boss', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .polarArray(p["bolt_r"], 0, 360, p["n_bolts"])
        .hole(p["bolt_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["plate_w"], p["plate_d"]) * 0.05820730444475615)
    result = (
        result.faces('>Z').workplane()
        .circle(p["boss_d"] / 2).extrude(p["boss_h"])
    )
    result = (
        result.faces('>Z').workplane()
        .hole(p["boss_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
