import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234004029 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 74.46, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 38.9, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 2.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "bolt_d": {"type": 'float', "default": 3.2, "min": 3.0, "max": 13.0, "step": 0.1, "group": 'Holes', "label": 'Bolt hole diameter (mm)'},
    "bolt_r": {"type": 'float', "default": 22.3, "min": 14.9, "max": 33.5, "step": 1.0, "group": 'Holes', "label": 'Bolt circle radius (mm)'},
    "n_bolts": {"type": 'int', "default": 4, "min": 3, "max": 12, "step": 1, "group": 'Holes', "label": 'Number of bolts'},
    "filleted": {"type": 'bool', "default": True, "group": 'Body', "label": 'Fillet corners'},
    "pocket_w": {"type": 'float', "default": 45.2, "min": 22.6, "max": 59.6, "step": 1.0, "group": 'Pocket', "label": 'Pocket width (mm)'},
    "pocket_d": {"type": 'float', "default": 22.0, "min": 11.0, "max": 31.1, "step": 1.0, "group": 'Pocket', "label": 'Pocket depth (mm)'},
    "pocket_h": {"type": 'float', "default": 1.0, "min": 0.4, "max": 1.7, "step": 0.5, "group": 'Pocket', "label": 'Pocket height (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    result = (
        result.faces('>Z').workplane()
        .polarArray(p["bolt_r"], 0, 360, p["n_bolts"])
        .hole(p["bolt_d"])
    )
    if p["filleted"]:
        result = result.edges('|Z').fillet(min(p["plate_w"], p["plate_d"]) * 0.09150538615650997)
    result = (
        result.faces('>Z').workplane()
        .rect(p["pocket_w"], p["pocket_d"])
        .cutBlind(-p["pocket_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
