import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004617 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "plate_w": {"type": 'float', "default": 60, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 24.5, "min": 8.0, "max": 120.0, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
    "thickness": {"type": 'float', "default": 10.0, "min": 2.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Thickness (mm)'},
    "hole_d": {"type": 'float', "default": 2.3, "min": 2.0, "max": 2.5, "step": 0.1, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "hole_nx": {"type": 'int', "default": 4, "min": 2, "max": 5, "step": 1, "group": 'Holes', "label": 'Holes per row'},
}


def build(p):

    result = cq.Workplane('XY').box(p["plate_w"], p["plate_d"], p["thickness"])
    _snx = max(2, int(p["hole_nx"]))
    _ssx = 15.0
    _ssy = 15.6
    _spts = (
        [(-_ssx * (_snx - 1) / 2 + _ssx * _i, -_ssy / 2) for _i in range(_snx)]
        + [(-_ssx * (_snx - 2) / 2 + _ssx * _i, _ssy / 2) for _i in range(_snx - 1)]
    )
    result = (
        result.faces('>Z').workplane()
        .pushPoints(_spts)
        .hole(p["hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
