import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234004449 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 25, "min": 12.5, "max": 50.0, "step": 1.0, "group": 'Profile', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 186.9, "min": 56.1, "max": 560.7, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
