import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004413 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 28.67, "min": 14.3, "max": 51.6, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 44.95, "min": 22.5, "max": 80.9, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "length": {"type": 'float', "default": 144.7, "min": 43.4, "max": 434.1, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.4789, p["sk_h"] * 0.1174).spline([(p["sk_w"] * 0.4789, p["sk_h"] * 0.1174), (p["sk_w"] * 0.401, p["sk_h"] * 0.207), (p["sk_w"] * 0.2981, p["sk_h"] * 0.2662)]).threePointArc((p["sk_w"] * 0.0933, p["sk_h"] * 0.3271), (p["sk_w"] * -0.1313, p["sk_h"] * 0.2962)).threePointArc((p["sk_w"] * -0.3476, p["sk_h"] * 0.2635), (p["sk_w"] * -0.4714, p["sk_h"] * 0.1584)).threePointArc((p["sk_w"] * -0.4365, p["sk_h"] * -0.037), (p["sk_w"] * -0.2705, p["sk_h"] * -0.2282)).lineTo(p["sk_w"] * -0.023, p["sk_h"] * -0.4158).threePointArc((p["sk_w"] * 0.1165, p["sk_h"] * -0.4117), (p["sk_w"] * 0.2424, p["sk_h"] * -0.3541)).lineTo(p["sk_w"] * 0.4789, p["sk_h"] * 0.1174).close().extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
