import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004325 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "slot_len": {"type": 'float', "default": 70.09, "min": 35.0, "max": 140.2, "step": 1.0, "group": 'Profile', "label": 'Slot length (mm)'},
    "slot_w": {"type": 'float', "default": 24.52, "min": 12.3, "max": 49.0, "step": 0.5, "group": 'Profile', "label": 'Slot width (mm)'},
    "length": {"type": 'float', "default": 412.5, "min": 123.8, "max": 1237.5, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').slot2D(p["slot_len"], p["slot_w"]).extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
