import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004222 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 40, "min": 20.0, "max": 72.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 42.35, "min": 21.2, "max": 76.2, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "length": {"type": 'float', "default": 181.5, "min": 54.4, "max": 544.5, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.4372, p["sk_h"] * -0.0308).lineTo(p["sk_w"] * 0.011, p["sk_h"] * 0.3282).lineTo(p["sk_w"] * -0.3813, p["sk_h"] * 0.2339).threePointArc((p["sk_w"] * -0.4145, p["sk_h"] * 0.015), (p["sk_w"] * -0.3219, p["sk_h"] * -0.2059)).threePointArc((p["sk_w"] * -0.0635, p["sk_h"] * -0.2789), (p["sk_w"] * 0.2079, p["sk_h"] * -0.2825)).bezier([(p["sk_w"] * 0.2079, p["sk_h"] * -0.2825), (p["sk_w"] * 0.341, p["sk_h"] * -0.1735), (p["sk_w"] * 0.4372, p["sk_h"] * -0.0308)]).close().extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
