import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004470 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 16.91, "min": 8.5, "max": 33.8, "step": 1.0, "group": 'Profile', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 130.8, "min": 39.2, "max": 392.4, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
