import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234003716 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 45.88, "min": 22.9, "max": 91.8, "step": 1.0, "group": 'Profile', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 232.5, "min": 69.8, "max": 697.5, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
    "inner_d": {"type": 'float', "default": 24.9, "min": 2.0, "max": 36.7, "step": 0.5, "group": 'Profile', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(p["inner_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["length"])
        .lineTo(p["inner_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
