import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004252 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "circ_r": {"type": 'float', "default": 14.42, "min": 7.2, "max": 28.8, "step": 1.0, "group": 'Profile', "label": 'Circumscribed radius (mm)'},
    "n_sides": {"type": 'int', "default": 8, "min": 3, "max": 8, "step": 1, "group": 'Profile', "label": 'Sides'},
    "length": {"type": 'float', "default": 75.5, "min": 22.6, "max": 226.5, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["n_sides"], p["circ_r"] * 2).extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
