import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234003745 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "circ_r": {"type": 'float', "default": 22.84, "min": 11.4, "max": 45.7, "step": 1.0, "group": 'Profile', "label": 'Circumscribed radius (mm)'},
    "n_sides": {"type": 'int', "default": 4, "min": 3, "max": 8, "step": 1, "group": 'Profile', "label": 'Sides'},
    "length": {"type": 'float', "default": 95.6, "min": 28.7, "max": 286.8, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["n_sides"], p["circ_r"] * 2).extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
