import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234004718 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 9.28, "min": 4.6, "max": 18.6, "step": 1.0, "group": 'Profile', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 44.9, "min": 13.5, "max": 134.7, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
    "inner_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 7.4, "step": 0.5, "group": 'Profile', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(p["inner_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["length"])
        .lineTo(p["inner_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
