import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003749 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 35, "min": 17.5, "max": 70.0, "step": 1.0, "group": 'Profile', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 226.9, "min": 68.1, "max": 680.7, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
