import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004561 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 33.06, "min": 16.5, "max": 59.5, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 55, "min": 27.5, "max": 99.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "length": {"type": 'float', "default": 109.4, "min": 32.8, "max": 328.2, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.4832, p["sk_h"] * 0.0556).threePointArc((p["sk_w"] * 0.4456, p["sk_h"] * 0.1999), (p["sk_w"] * 0.3307, p["sk_h"] * 0.3073)).bezier([(p["sk_w"] * 0.3307, p["sk_h"] * 0.3073), (p["sk_w"] * 0.0258, p["sk_h"] * 0.3178), (p["sk_w"] * -0.2716, p["sk_h"] * 0.2495)]).lineTo(p["sk_w"] * -0.4601, p["sk_h"] * 0.0645).lineTo(p["sk_w"] * -0.2542, p["sk_h"] * -0.3223).lineTo(p["sk_w"] * 0.3245, p["sk_h"] * -0.363).lineTo(p["sk_w"] * 0.4832, p["sk_h"] * 0.0556).close().extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
