import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004554 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 41.56, "min": 20.8, "max": 74.8, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 55.18, "min": 27.6, "max": 99.3, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "length": {"type": 'float', "default": 197.5, "min": 59.2, "max": 592.5, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.4571, p["sk_h"] * -0.1229).lineTo(p["sk_w"] * 0.29, p["sk_h"] * 0.2539).lineTo(p["sk_w"] * -0.1354, p["sk_h"] * 0.3484).bezier([(p["sk_w"] * -0.1354, p["sk_h"] * 0.3484), (p["sk_w"] * -0.2673, p["sk_h"] * 0.2146), (p["sk_w"] * -0.3654, p["sk_h"] * 0.0544)]).lineTo(p["sk_w"] * -0.3545, p["sk_h"] * -0.3337).spline([(p["sk_w"] * -0.3545, p["sk_h"] * -0.3337), (p["sk_w"] * -0.2001, p["sk_h"] * -0.4048), (p["sk_w"] * -0.0312, p["sk_h"] * -0.386)]).spline([(p["sk_w"] * -0.0312, p["sk_h"] * -0.386), (p["sk_w"] * 0.1222, p["sk_h"] * -0.4184), (p["sk_w"] * 0.269, p["sk_h"] * -0.3636)]).spline([(p["sk_w"] * 0.269, p["sk_h"] * -0.3636), (p["sk_w"] * 0.3865, p["sk_h"] * -0.2616), (p["sk_w"] * 0.4571, p["sk_h"] * -0.1229)]).close().extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
