import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234003867 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 41.56, "min": 20.8, "max": 83.1, "step": 1.0, "group": 'Profile', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 300.0, "min": 90.0, "max": 900.0, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
