import cadquery as cq

# Generated by CadQuarry v0.1.0 — seed 1234004017 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "slot_len": {"type": 'float', "default": 24.01, "min": 12.0, "max": 48.0, "step": 1.0, "group": 'Profile', "label": 'Slot length (mm)'},
    "slot_w": {"type": 'float', "default": 10, "min": 5.0, "max": 20.0, "step": 0.5, "group": 'Profile', "label": 'Slot width (mm)'},
    "length": {"type": 'float', "default": 115.4, "min": 34.6, "max": 346.2, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').slot2D(p["slot_len"], p["slot_w"]).extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
