import cadquery as cq

# Generated by CadQuarry v0.4.0 — seed 1234004713 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "slot_len": {"type": 'float', "default": 69.38, "min": 34.7, "max": 138.8, "step": 1.0, "group": 'Profile', "label": 'Slot length (mm)'},
    "slot_w": {"type": 'float', "default": 20, "min": 10.0, "max": 40.0, "step": 0.5, "group": 'Profile', "label": 'Slot width (mm)'},
    "length": {"type": 'float', "default": 388.8, "min": 116.6, "max": 1166.4, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').slot2D(p["slot_len"], p["slot_w"]).extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
