import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004418 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "slot_len": {"type": 'float', "default": 25, "min": 12.5, "max": 50.0, "step": 1.0, "group": 'Profile', "label": 'Slot length (mm)'},
    "slot_w": {"type": 'float', "default": 20.15, "min": 10.1, "max": 40.3, "step": 0.5, "group": 'Profile', "label": 'Slot width (mm)'},
    "length": {"type": 'float', "default": 238.4, "min": 71.5, "max": 715.2, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').slot2D(p["slot_len"], p["slot_w"]).extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
