import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234003891 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "circ_r": {"type": 'float', "default": 10.58, "min": 5.3, "max": 21.2, "step": 1.0, "group": 'Profile', "label": 'Circumscribed radius (mm)'},
    "n_sides": {"type": 'int', "default": 3, "min": 3, "max": 8, "step": 1, "group": 'Profile', "label": 'Sides'},
    "length": {"type": 'float', "default": 47.3, "min": 14.2, "max": 141.9, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').polygon(p["n_sides"], p["circ_r"] * 2).extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
