import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234004770 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "slot_len": {"type": 'float', "default": 24.12, "min": 12.1, "max": 48.2, "step": 1.0, "group": 'Profile', "label": 'Slot length (mm)'},
    "slot_w": {"type": 'float', "default": 23.41, "min": 11.7, "max": 46.8, "step": 0.5, "group": 'Profile', "label": 'Slot width (mm)'},
    "length": {"type": 'float', "default": 99.7, "min": 29.9, "max": 299.1, "step": 5.0, "group": 'Body', "label": 'Length (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').slot2D(p["slot_len"], p["slot_w"]).extrude(p["length"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
