import cadquery as cq

# Generated by CadQuarry v0.1.0 — seed 1234003896 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 46.87, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 132.6, "min": 39.8, "max": 320.0, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "inner_d": {"type": 'float', "default": 17.0, "min": 2.0, "max": 32.8, "step": 0.5, "group": 'Body', "label": 'Bore diameter (mm)'},
    "end_chamfer": {"type": 'float', "default": 0.3, "min": 0.1, "max": 0.9, "step": 0.1, "group": 'Body', "label": 'End chamfer (mm)'},
    "end_chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'End chamfers'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(p["inner_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["length"])
        .lineTo(p["inner_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    if p["end_chamfered"]:
        result = result.edges('>Z or <Z').chamfer(p["end_chamfer"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
