import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004168 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 71.52, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 84.4, "min": 25.3, "max": 253.2, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "inner_d": {"type": 'float', "default": 25.7, "min": 2.0, "max": 50.1, "step": 0.5, "group": 'Body', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(p["inner_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["length"])
        .lineTo(p["inner_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
