import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234004351 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 65, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 200.5, "min": 60.1, "max": 320.0, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "flange_d": {"type": 'float', "default": 91.0, "min": 78.0, "max": 195.0, "step": 1.0, "group": 'Body', "label": 'Flange diameter (mm)'},
    "flange_h": {"type": 'float', "default": 56.6, "min": 17.0, "max": 100.2, "step": 0.5, "group": 'Body', "label": 'Flange height (mm)'},
    "groove_depth": {"type": 'float', "default": 3.38, "min": 1.35, "max": 10.14, "step": 0.1, "group": 'Body', "label": 'Groove depth (mm)'},
    "groove_w": {"type": 'float', "default": 19.61, "min": 7.84, "max": 58.83, "step": 0.2, "group": 'Body', "label": 'Groove width (mm)'},
    "groove_pos": {"type": 'float', "default": 87.8, "min": 30.1, "max": 170.4, "step": 1.0, "group": 'Body', "label": 'Groove position (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["flange_d"] / 2, 0)
        .lineTo(p["flange_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["groove_pos"] - p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2 - p["groove_depth"], p["groove_pos"] - p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2 - p["groove_depth"], p["groove_pos"] + p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2, p["groove_pos"] + p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
