import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234003713 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 40.83, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 47.4, "min": 14.2, "max": 142.2, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "inner_d": {"type": 'float', "default": 18.1, "min": 2.0, "max": 28.6, "step": 0.5, "group": 'Body', "label": 'Bore diameter (mm)'},
    "end_chamfer": {"type": 'float', "default": 0.4, "min": 0.1, "max": 1.2, "step": 0.1, "group": 'Body', "label": 'End chamfer (mm)'},
    "end_chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'End chamfers'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(p["inner_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["length"])
        .lineTo(p["inner_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    if p["end_chamfered"]:
        result = result.edges('>Z or <Z').chamfer(p["end_chamfer"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
