import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004035 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 54.44, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 138.3, "min": 41.5, "max": 320.0, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "inner_d": {"type": 'float', "default": 18.4, "min": 2.0, "max": 38.1, "step": 0.5, "group": 'Body', "label": 'Bore diameter (mm)'},
    "flange_d": {"type": 'float', "default": 105.8, "min": 65.3, "max": 163.3, "step": 1.0, "group": 'Body', "label": 'Flange diameter (mm)'},
    "flange_h": {"type": 'float', "default": 27.4, "min": 8.2, "max": 69.2, "step": 0.5, "group": 'Body', "label": 'Flange height (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(p["inner_d"] / 2, 0)
        .lineTo(p["flange_d"] / 2, 0)
        .lineTo(p["flange_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["length"])
        .lineTo(p["inner_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
