import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004753 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 8.71, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 7.5, "min": 2.2, "max": 22.5, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "groove_depth": {"type": 'float', "default": 0.46, "min": 0.18, "max": 1.38, "step": 0.1, "group": 'Body', "label": 'Groove depth (mm)'},
    "groove_w": {"type": 'float', "default": 0.46, "min": 0.18, "max": 1.38, "step": 0.2, "group": 'Body', "label": 'Groove width (mm)'},
    "groove_pos": {"type": 'float', "default": 4.0, "min": 1.1, "max": 6.4, "step": 1.0, "group": 'Body', "label": 'Groove position (mm)'},
    "end_chamfer": {"type": 'float', "default": 1.0, "min": 0.1, "max": 3.0, "step": 0.1, "group": 'Body', "label": 'End chamfer (mm)'},
    "end_chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'End chamfers'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["groove_pos"] - p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2 - p["groove_depth"], p["groove_pos"] - p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2 - p["groove_depth"], p["groove_pos"] + p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2, p["groove_pos"] + p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    if p["end_chamfered"]:
        result = result.edges('>Z or <Z').chamfer(p["end_chamfer"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
