import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234003990 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 28.57, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 19.6, "min": 5.9, "max": 58.8, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "flange_d": {"type": 'float', "default": 40.3, "min": 34.3, "max": 85.7, "step": 1.0, "group": 'Body', "label": 'Flange diameter (mm)'},
    "flange_h": {"type": 'float', "default": 4.5, "min": 1.3, "max": 9.8, "step": 0.5, "group": 'Body', "label": 'Flange height (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["flange_d"] / 2, 0)
        .lineTo(p["flange_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
