import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004412 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 32.35, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 75.2, "min": 22.6, "max": 225.6, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "flange_d": {"type": 'float', "default": 58.4, "min": 38.8, "max": 97.1, "step": 1.0, "group": 'Body', "label": 'Flange diameter (mm)'},
    "flange_h": {"type": 'float', "default": 17.4, "min": 5.2, "max": 37.6, "step": 0.5, "group": 'Body', "label": 'Flange height (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["flange_d"] / 2, 0)
        .lineTo(p["flange_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
