import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004120 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 50, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 117.8, "min": 35.3, "max": 320.0, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "flange_d": {"type": 'float', "default": 70.2, "min": 60.0, "max": 150.0, "step": 1.0, "group": 'Body', "label": 'Flange diameter (mm)'},
    "flange_h": {"type": 'float', "default": 15.7, "min": 4.7, "max": 58.9, "step": 0.5, "group": 'Body', "label": 'Flange height (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["flange_d"] / 2, 0)
        .lineTo(p["flange_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
