import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003949 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 65.5, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 24.6, "min": 7.4, "max": 73.8, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "groove_depth": {"type": 'float', "default": 3.44, "min": 1.38, "max": 10.32, "step": 0.1, "group": 'Body', "label": 'Groove depth (mm)'},
    "groove_w": {"type": 'float', "default": 2.37, "min": 0.95, "max": 7.11, "step": 0.2, "group": 'Body', "label": 'Groove width (mm)'},
    "groove_pos": {"type": 'float', "default": 7.4, "min": 3.7, "max": 20.9, "step": 1.0, "group": 'Body', "label": 'Groove position (mm)'},
    "end_chamfer": {"type": 'float', "default": 0.6, "min": 0.1, "max": 1.8, "step": 0.1, "group": 'Body', "label": 'End chamfer (mm)'},
    "end_chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'End chamfers'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["groove_pos"] - p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2 - p["groove_depth"], p["groove_pos"] - p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2 - p["groove_depth"], p["groove_pos"] + p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2, p["groove_pos"] + p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    if p["end_chamfered"]:
        result = result.edges('>Z or <Z').chamfer(p["end_chamfer"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
