import cadquery as cq

# Generated by CadQuarry v0.5.0 — seed 1234004781 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 43.06, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 135.0, "min": 40.5, "max": 320.0, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "inner_d": {"type": 'float', "default": 21.5, "min": 2.0, "max": 30.1, "step": 0.5, "group": 'Body', "label": 'Bore diameter (mm)'},
    "groove_depth": {"type": 'float', "default": 3.41, "min": 1.36, "max": 10.23, "step": 0.1, "group": 'Body', "label": 'Groove depth (mm)'},
    "groove_w": {"type": 'float', "default": 10.63, "min": 4.25, "max": 31.89, "step": 0.2, "group": 'Body', "label": 'Groove width (mm)'},
    "groove_pos": {"type": 'float', "default": 53.5, "min": 20.2, "max": 114.8, "step": 1.0, "group": 'Body', "label": 'Groove position (mm)'},
    "end_chamfer": {"type": 'float', "default": 0.8, "min": 0.1, "max": 2.4, "step": 0.1, "group": 'Body', "label": 'End chamfer (mm)'},
    "end_chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'End chamfers'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(p["inner_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["groove_pos"] - p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2 - p["groove_depth"], p["groove_pos"] - p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2 - p["groove_depth"], p["groove_pos"] + p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2, p["groove_pos"] + p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2, p["length"])
        .lineTo(p["inner_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    if p["end_chamfered"]:
        result = result.edges('>Z or <Z').chamfer(p["end_chamfer"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
