import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234003970 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 66.19, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 246.6, "min": 74.0, "max": 320.0, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "inner_d": {"type": 'float', "default": 25.9, "min": 2.0, "max": 46.3, "step": 0.5, "group": 'Body', "label": 'Bore diameter (mm)'},
    "groove_depth": {"type": 'float', "default": 2.73, "min": 1.09, "max": 8.19, "step": 0.1, "group": 'Body', "label": 'Groove depth (mm)'},
    "groove_w": {"type": 'float', "default": 17.66, "min": 7.06, "max": 52.98, "step": 0.2, "group": 'Body', "label": 'Groove width (mm)'},
    "groove_pos": {"type": 'float', "default": 111.5, "min": 37.0, "max": 209.6, "step": 1.0, "group": 'Body', "label": 'Groove position (mm)'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(p["inner_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["groove_pos"] - p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2 - p["groove_depth"], p["groove_pos"] - p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2 - p["groove_depth"], p["groove_pos"] + p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2, p["groove_pos"] + p["groove_w"] / 2)
        .lineTo(p["outer_d"] / 2, p["length"])
        .lineTo(p["inner_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
