import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234003850 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 41.16, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 21.7, "min": 6.5, "max": 65.1, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "end_chamfer": {"type": 'float', "default": 1.0, "min": 0.1, "max": 3.0, "step": 0.1, "group": 'Body', "label": 'End chamfer (mm)'},
    "end_chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'End chamfers'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["outer_d"] / 2, 0)
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    if p["end_chamfered"]:
        result = result.edges('>Z or <Z').chamfer(p["end_chamfer"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
