import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003875 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "outer_d": {"type": 'float', "default": 20.91, "min": 6.0, "max": 80.0, "step": 1.0, "group": 'Body', "label": 'Outer diameter (mm)'},
    "length": {"type": 'float', "default": 10.2, "min": 3.1, "max": 30.6, "step": 1.0, "group": 'Body', "label": 'Length (mm)'},
    "flange_d": {"type": 'float', "default": 31.9, "min": 25.1, "max": 62.7, "step": 1.0, "group": 'Body', "label": 'Flange diameter (mm)'},
    "flange_h": {"type": 'float', "default": 1.8, "min": 0.5, "max": 5.1, "step": 0.5, "group": 'Body', "label": 'Flange height (mm)'},
    "end_chamfer": {"type": 'float', "default": 1.4, "min": 0.1, "max": 4.2, "step": 0.1, "group": 'Body', "label": 'End chamfer (mm)'},
    "end_chamfered": {"type": 'bool', "default": True, "group": 'Body', "label": 'End chamfers'},
}


def build(p):

    result = (
        cq.Workplane('XZ')
        .moveTo(0, 0)
        .lineTo(p["flange_d"] / 2, 0)
        .lineTo(p["flange_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["flange_h"])
        .lineTo(p["outer_d"] / 2, p["length"])
        .close()
        .revolve()
    )
    if p["end_chamfered"]:
        result = result.edges('>Z or <Z').chamfer(p["end_chamfer"])
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
