import cadquery as cq

# Generated by CadQuarry v0.3.0 — seed 1234004008 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "base_w": {"type": 'float', "default": 90.71, "min": 20.0, "max": 120.0, "step": 1.0, "group": 'Base', "label": 'Base width (mm)'},
    "base_d": {"type": 'float', "default": 56.5, "min": 15.0, "max": 120.0, "step": 1.0, "group": 'Base', "label": 'Base depth (mm)'},
    "base_t": {"type": 'float', "default": 10.0, "min": 2.0, "max": 15.0, "step": 0.5, "group": 'Base', "label": 'Base thickness (mm)'},
    "rib_count": {"type": 'int', "default": 4, "min": 2, "max": 8, "step": 1, "group": 'Ribs', "label": 'Rib count'},
    "rib_h": {"type": 'float', "default": 16.9, "min": 6.8, "max": 33.8, "step": 1.0, "group": 'Ribs', "label": 'Rib height (mm)'},
    "rib_t": {"type": 'float', "default": 2.9, "min": 1.0, "max": 7.2, "step": 0.5, "group": 'Ribs', "label": 'Rib thickness (mm)'},
}


def build(p):

    result = cq.Workplane('XY').box(p["base_w"], p["base_d"], p["base_t"])
    _rib_spacing = (p["base_w"] * 0.8 / (p["rib_count"] - 1)) if p["rib_count"] > 1 else 0
    result = (
        result.faces('>Z').workplane()
        .rarray(_rib_spacing, 1, p["rib_count"], 1)
        .rect(p["rib_t"], p["base_w"] * 0.8).extrude(p["rib_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
