import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004401 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_r": {"type": 'float', "default": 15, "min": 7.5, "max": 27.0, "step": 1.0, "group": 'Sketch', "label": 'Max radius (mm)'},
    "sk_h": {"type": 'float', "default": 31.11, "min": 15.6, "max": 56.0, "step": 1.0, "group": 'Sketch', "label": 'Height (mm)'},
}


def build(p):

    result = (cq.Workplane('XZ').moveTo(p["sk_r"] * 0.2283, p["sk_h"] * 0.0).threePointArc((p["sk_r"] * 0.569, p["sk_h"] * 0.0834), (p["sk_r"] * 0.8955, p["sk_h"] * 0.1667)).threePointArc((p["sk_r"] * 0.6026, p["sk_h"] * 0.2452), (p["sk_r"] * 0.4459, p["sk_h"] * 0.3237)).lineTo(p["sk_r"] * 0.4357, p["sk_h"] * 0.3372).lineTo(p["sk_r"] * 0.5819, p["sk_h"] * 0.7288).bezier([(p["sk_r"] * 0.5819, p["sk_h"] * 0.7288), (p["sk_r"] * 0.6379, p["sk_h"] * 0.8243), (p["sk_r"] * 0.6401, p["sk_h"] * 0.9197)]).spline([(p["sk_r"] * 0.6401, p["sk_h"] * 0.9197), (p["sk_r"] * 0.5839, p["sk_h"] * 0.9599), (p["sk_r"] * 0.2886, p["sk_h"] * 1.0)]).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 0.0).close().revolve())
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
