import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004397 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 70, "min": 35.0, "max": 126.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 56.78, "min": 28.4, "max": 102.2, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 12.94, "min": 5.2, "max": 28.5, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "sk_hole_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 8.6, "step": 0.5, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.451, p["sk_h"] * -0.0826).lineTo(p["sk_w"] * -0.1907, p["sk_h"] * 0.3572).spline([(p["sk_w"] * -0.1907, p["sk_h"] * 0.3572), (p["sk_w"] * -0.3717, p["sk_h"] * 0.1874), (p["sk_w"] * -0.4422, p["sk_h"] * -0.0506)]).lineTo(p["sk_w"] * 0.1101, p["sk_h"] * -0.3026).lineTo(p["sk_w"] * 0.451, p["sk_h"] * -0.0826).close().extrude(p["sk_t"]))
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["sk_hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
