import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004075 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_r": {"type": 'float', "default": 20, "min": 10.0, "max": 36.0, "step": 1.0, "group": 'Sketch', "label": 'Max radius (mm)'},
    "sk_h": {"type": 'float', "default": 30, "min": 15.0, "max": 54.0, "step": 1.0, "group": 'Sketch', "label": 'Height (mm)'},
}


def build(p):

    result = (cq.Workplane('XZ').moveTo(p["sk_r"] * 0.1582, p["sk_h"] * 0.0).bezier([(p["sk_r"] * 0.1582, p["sk_h"] * 0.0), (p["sk_r"] * 0.4168, p["sk_h"] * 0.2149), (p["sk_r"] * 0.3548, p["sk_h"] * 0.4299)]).lineTo(p["sk_r"] * 0.5396, p["sk_h"] * 0.5798).lineTo(p["sk_r"] * 0.9254, p["sk_h"] * 0.7468).spline([(p["sk_r"] * 0.9254, p["sk_h"] * 0.7468), (p["sk_r"] * 0.4721, p["sk_h"] * 0.8435), (p["sk_r"] * 0.2255, p["sk_h"] * 0.9401)]).lineTo(p["sk_r"] * 0.4747, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 0.0).close().revolve())
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
