import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004121 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_r": {"type": 'float', "default": 39.16, "min": 19.6, "max": 70.5, "step": 1.0, "group": 'Sketch', "label": 'Max radius (mm)'},
    "sk_h": {"type": 'float', "default": 40.32, "min": 20.2, "max": 72.6, "step": 1.0, "group": 'Sketch', "label": 'Height (mm)'},
}


def build(p):

    result = (cq.Workplane('XZ').moveTo(p["sk_r"] * 0.6284, p["sk_h"] * 0.0).bezier([(p["sk_r"] * 0.6284, p["sk_h"] * 0.0), (p["sk_r"] * 0.5353, p["sk_h"] * 0.0622), (p["sk_r"] * 0.3146, p["sk_h"] * 0.1245)]).lineTo(p["sk_r"] * 0.9415, p["sk_h"] * 0.3133).threePointArc((p["sk_r"] * 0.5986, p["sk_h"] * 0.3609), (p["sk_r"] * 0.2883, p["sk_h"] * 0.4085)).lineTo(p["sk_r"] * 0.555, p["sk_h"] * 0.4527).lineTo(p["sk_r"] * 0.2813, p["sk_h"] * 0.9465).bezier([(p["sk_r"] * 0.2813, p["sk_h"] * 0.9465), (p["sk_r"] * 0.6228, p["sk_h"] * 0.9733), (p["sk_r"] * 0.7598, p["sk_h"] * 1.0)]).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 0.0).close().revolve())
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
