import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003742 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_r": {"type": 'float', "default": 39.64, "min": 19.8, "max": 71.4, "step": 1.0, "group": 'Sketch', "label": 'Max radius (mm)'},
    "sk_h": {"type": 'float', "default": 70.0, "min": 35.0, "max": 126.0, "step": 1.0, "group": 'Sketch', "label": 'Height (mm)'},
}


def build(p):

    result = (cq.Workplane('XZ').moveTo(p["sk_r"] * 0.7571, p["sk_h"] * 0.0).threePointArc((p["sk_r"] * 0.6608, p["sk_h"] * 0.0778), (p["sk_r"] * 0.6213, p["sk_h"] * 0.1556)).bezier([(p["sk_r"] * 0.6213, p["sk_h"] * 0.1556), (p["sk_r"] * 0.838, p["sk_h"] * 0.1724), (p["sk_r"] * 0.7255, p["sk_h"] * 0.1891)]).spline([(p["sk_r"] * 0.7255, p["sk_h"] * 0.1891), (p["sk_r"] * 0.3429, p["sk_h"] * 0.2654), (p["sk_r"] * 0.136, p["sk_h"] * 0.3417)]).lineTo(p["sk_r"] * 0.6446, p["sk_h"] * 0.8377).threePointArc((p["sk_r"] * 0.6151, p["sk_h"] * 0.8669), (p["sk_r"] * 0.6234, p["sk_h"] * 0.896)).spline([(p["sk_r"] * 0.6234, p["sk_h"] * 0.896), (p["sk_r"] * 0.5745, p["sk_h"] * 0.948), (p["sk_r"] * 0.3595, p["sk_h"] * 1.0)]).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 0.0).close().revolve())
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
