import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004118 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 65, "min": 32.5, "max": 117.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 45, "min": 22.5, "max": 81.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 15, "min": 6.0, "max": 33.0, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "sk_hole_d": {"type": 'float', "default": 6.4, "min": 2.0, "max": 12.8, "step": 0.5, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.3763, p["sk_h"] * -0.0357).threePointArc((p["sk_w"] * 0.4063, p["sk_h"] * 0.1322), (p["sk_w"] * 0.3439, p["sk_h"] * 0.2661)).spline([(p["sk_w"] * 0.3439, p["sk_h"] * 0.2661), (p["sk_w"] * 0.1696, p["sk_h"] * 0.3499), (p["sk_w"] * -0.0234, p["sk_h"] * 0.3633)]).threePointArc((p["sk_w"] * -0.2659, p["sk_h"] * 0.2959), (p["sk_w"] * -0.4483, p["sk_h"] * 0.1606)).threePointArc((p["sk_w"] * -0.4356, p["sk_h"] * -0.0546), (p["sk_w"] * -0.2988, p["sk_h"] * -0.2584)).threePointArc((p["sk_w"] * -0.249, p["sk_h"] * -0.2874), (p["sk_w"] * -0.1662, p["sk_h"] * -0.2812)).spline([(p["sk_w"] * -0.1662, p["sk_h"] * -0.2812), (p["sk_w"] * 0.0509, p["sk_h"] * -0.3564), (p["sk_w"] * 0.2763, p["sk_h"] * -0.3122)]).lineTo(p["sk_w"] * 0.3763, p["sk_h"] * -0.0357).close().extrude(p["sk_t"]))
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["sk_hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
