import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004607 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_r": {"type": 'float', "default": 29.37, "min": 14.7, "max": 52.9, "step": 1.0, "group": 'Sketch', "label": 'Max radius (mm)'},
    "sk_h": {"type": 'float', "default": 35, "min": 17.5, "max": 63.0, "step": 1.0, "group": 'Sketch', "label": 'Height (mm)'},
}


def build(p):

    result = (cq.Workplane('XZ').moveTo(p["sk_r"] * 0.3422, p["sk_h"] * 0.0).threePointArc((p["sk_r"] * 0.3869, p["sk_h"] * 0.1857), (p["sk_r"] * 0.6066, p["sk_h"] * 0.3713)).lineTo(p["sk_r"] * 0.9903, p["sk_h"] * 0.4147).lineTo(p["sk_r"] * 0.2704, p["sk_h"] * 0.742).threePointArc((p["sk_r"] * 0.6666, p["sk_h"] * 0.871), (p["sk_r"] * 0.9449, p["sk_h"] * 1.0)).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 0.0).close().revolve())
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
