import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004730 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 79.55, "min": 39.8, "max": 143.2, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 75, "min": 37.5, "max": 135.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 17.09, "min": 6.8, "max": 37.6, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "sk_hole_d": {"type": 'float', "default": 8.4, "min": 2.0, "max": 16.8, "step": 0.5, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "boss_d": {"type": 'float', "default": 14.9, "min": 7.5, "max": 29.8, "step": 1.0, "group": 'Boss', "label": 'Boss diameter (mm)'},
    "boss_h": {"type": 'float', "default": 5.0, "min": 2.0, "max": 12.5, "step": 1.0, "group": 'Boss', "label": 'Boss height (mm)'},
    "boss_bore_d": {"type": 'float', "default": 3.2, "min": 2.0, "max": 10.4, "step": 0.1, "group": 'Boss', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.4493, p["sk_h"] * 0.088).spline([(p["sk_w"] * 0.4493, p["sk_h"] * 0.088), (p["sk_w"] * 0.3092, p["sk_h"] * 0.2683), (p["sk_w"] * 0.1111, p["sk_h"] * 0.3817)]).threePointArc((p["sk_w"] * 0.0122, p["sk_h"] * 0.3685), (p["sk_w"] * -0.0847, p["sk_h"] * 0.3144)).lineTo(p["sk_w"] * -0.3423, p["sk_h"] * -0.0857).lineTo(p["sk_w"] * -0.1542, p["sk_h"] * -0.4309).bezier([(p["sk_w"] * -0.1542, p["sk_h"] * -0.4309), (p["sk_w"] * 0.0338, p["sk_h"] * -0.3843), (p["sk_w"] * 0.2087, p["sk_h"] * -0.3012)]).lineTo(p["sk_w"] * 0.4493, p["sk_h"] * 0.088).close().extrude(p["sk_t"]))
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["sk_hole_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .circle(p["boss_d"] / 2).extrude(p["boss_h"])
    )
    result = (
        result.faces('>Z').workplane()
        .hole(p["boss_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
