import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003714 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 65, "min": 32.5, "max": 117.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 46.43, "min": 23.2, "max": 83.6, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 15, "min": 6.0, "max": 33.0, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "sk_hole_d": {"type": 'float', "default": 5.3, "min": 2.0, "max": 10.6, "step": 0.5, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "boss_d": {"type": 'float', "default": 13.9, "min": 7.0, "max": 27.8, "step": 1.0, "group": 'Boss', "label": 'Boss diameter (mm)'},
    "boss_h": {"type": 'float', "default": 7.5, "min": 3.0, "max": 18.8, "step": 1.0, "group": 'Boss', "label": 'Boss height (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.3253, p["sk_h"] * -0.0209).lineTo(p["sk_w"] * -0.0213, p["sk_h"] * 0.323).bezier([(p["sk_w"] * -0.0213, p["sk_h"] * 0.323), (p["sk_w"] * -0.2006, p["sk_h"] * 0.3026), (p["sk_w"] * -0.3593, p["sk_h"] * 0.2166)]).spline([(p["sk_w"] * -0.3593, p["sk_h"] * 0.2166), (p["sk_w"] * -0.3712, p["sk_h"] * -0.0854), (p["sk_w"] * -0.254, p["sk_h"] * -0.3641)]).lineTo(p["sk_w"] * 0.1607, p["sk_h"] * -0.4417).bezier([(p["sk_w"] * 0.1607, p["sk_h"] * -0.4417), (p["sk_w"] * 0.285, p["sk_h"] * -0.2477), (p["sk_w"] * 0.3253, p["sk_h"] * -0.0209)]).close().extrude(p["sk_t"]))
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["sk_hole_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .circle(p["boss_d"] / 2).extrude(p["boss_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
