import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003935 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 75, "min": 37.5, "max": 135.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 45, "min": 22.5, "max": 81.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 25, "min": 10.0, "max": 55.0, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "sk_hole_d": {"type": 'float', "default": 5.3, "min": 2.0, "max": 10.6, "step": 0.5, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.4785, p["sk_h"] * 0.0935).threePointArc((p["sk_w"] * 0.3638, p["sk_h"] * 0.2932), (p["sk_w"] * 0.1784, p["sk_h"] * 0.4377)).lineTo(p["sk_w"] * 0.0147, p["sk_h"] * 0.4268).lineTo(p["sk_w"] * -0.3509, p["sk_h"] * 0.1959).spline([(p["sk_w"] * -0.3509, p["sk_h"] * 0.1959), (p["sk_w"] * -0.402, p["sk_h"] * 0.0659), (p["sk_w"] * -0.3902, p["sk_h"] * -0.0733)]).bezier([(p["sk_w"] * -0.3902, p["sk_h"] * -0.0733), (p["sk_w"] * -0.2012, p["sk_h"] * -0.2752), (p["sk_w"] * 0.0317, p["sk_h"] * -0.4244)]).lineTo(p["sk_w"] * 0.2448, p["sk_h"] * -0.4336).lineTo(p["sk_w"] * 0.4785, p["sk_h"] * 0.0935).close().extrude(p["sk_t"]))
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["sk_hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
