import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004568 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_r": {"type": 'float', "default": 25, "min": 12.5, "max": 45.0, "step": 1.0, "group": 'Sketch', "label": 'Max radius (mm)'},
    "sk_h": {"type": 'float', "default": 60, "min": 30.0, "max": 108.0, "step": 1.0, "group": 'Sketch', "label": 'Height (mm)'},
}


def build(p):

    result = (cq.Workplane('XZ').moveTo(p["sk_r"] * 0.7527, p["sk_h"] * 0.0).threePointArc((p["sk_r"] * 0.8165, p["sk_h"] * 0.1928), (p["sk_r"] * 0.8763, p["sk_h"] * 0.3855)).lineTo(p["sk_r"] * 0.966, p["sk_h"] * 0.5072).threePointArc((p["sk_r"] * 0.6337, p["sk_h"] * 0.6248), (p["sk_r"] * 0.3786, p["sk_h"] * 0.7424)).lineTo(p["sk_r"] * 0.5535, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.2156, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.2156, p["sk_h"] * 0.0).close().revolve())
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
