import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004539 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_r": {"type": 'float', "default": 25, "min": 12.5, "max": 45.0, "step": 1.0, "group": 'Sketch', "label": 'Max radius (mm)'},
    "sk_h": {"type": 'float', "default": 37.21, "min": 18.6, "max": 67.0, "step": 1.0, "group": 'Sketch', "label": 'Height (mm)'},
}


def build(p):

    result = (cq.Workplane('XZ').moveTo(p["sk_r"] * 0.6164, p["sk_h"] * 0.0).lineTo(p["sk_r"] * 0.1677, p["sk_h"] * 0.7042).bezier([(p["sk_r"] * 0.1677, p["sk_h"] * 0.7042), (p["sk_r"] * 0.6277, p["sk_h"] * 0.7711), (p["sk_r"] * 0.8719, p["sk_h"] * 0.8381)]).threePointArc((p["sk_r"] * 0.7446, p["sk_h"] * 0.8659), (p["sk_r"] * 0.4106, p["sk_h"] * 0.8937)).lineTo(p["sk_r"] * 0.5159, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.0, p["sk_h"] * 0.0).close().revolve())
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
