import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003886 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_r": {"type": 'float', "default": 25, "min": 12.5, "max": 45.0, "step": 1.0, "group": 'Sketch', "label": 'Max radius (mm)'},
    "sk_h": {"type": 'float', "default": 60, "min": 30.0, "max": 108.0, "step": 1.0, "group": 'Sketch', "label": 'Height (mm)'},
}


def build(p):

    result = (cq.Workplane('XZ').moveTo(p["sk_r"] * 0.511, p["sk_h"] * 0.0).lineTo(p["sk_r"] * 0.1741, p["sk_h"] * 0.1792).spline([(p["sk_r"] * 0.1741, p["sk_h"] * 0.1792), (p["sk_r"] * 0.5598, p["sk_h"] * 0.1933), (p["sk_r"] * 0.7772, p["sk_h"] * 0.2074)]).lineTo(p["sk_r"] * 0.2056, p["sk_h"] * 0.4041).lineTo(p["sk_r"] * 0.5656, p["sk_h"] * 0.7087).spline([(p["sk_r"] * 0.5656, p["sk_h"] * 0.7087), (p["sk_r"] * 0.5402, p["sk_h"] * 0.8544), (p["sk_r"] * 0.2757, p["sk_h"] * 1.0)]).lineTo(p["sk_r"] * 0.0709, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.0709, p["sk_h"] * 0.0).close().revolve())
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
