import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004261 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 70, "min": 35.0, "max": 126.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 80, "min": 40.0, "max": 144.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 15, "min": 6.0, "max": 33.0, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "sk_hole_d": {"type": 'float', "default": 6.4, "min": 2.0, "max": 12.8, "step": 0.5, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.4132, p["sk_h"] * -0.0343).lineTo(p["sk_w"] * 0.2996, p["sk_h"] * 0.3671).threePointArc((p["sk_w"] * 0.0609, p["sk_h"] * 0.4452), (p["sk_w"] * -0.1804, p["sk_h"] * 0.4308)).threePointArc((p["sk_w"] * -0.3362, p["sk_h"] * 0.2857), (p["sk_w"] * -0.4367, p["sk_h"] * 0.1058)).bezier([(p["sk_w"] * -0.4367, p["sk_h"] * 0.1058), (p["sk_w"] * -0.3146, p["sk_h"] * -0.1396), (p["sk_w"] * -0.1002, p["sk_h"] * -0.3104)]).bezier([(p["sk_w"] * -0.1002, p["sk_h"] * -0.3104), (p["sk_w"] * 0.103, p["sk_h"] * -0.346), (p["sk_w"] * 0.3046, p["sk_h"] * -0.302)]).bezier([(p["sk_w"] * 0.3046, p["sk_h"] * -0.302), (p["sk_w"] * 0.3834, p["sk_h"] * -0.1781), (p["sk_w"] * 0.4132, p["sk_h"] * -0.0343)]).close().extrude(p["sk_t"]))
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["sk_hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
