import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004198 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 50, "min": 25.0, "max": 90.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 57.91, "min": 29.0, "max": 104.2, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 6.59, "min": 2.6, "max": 14.5, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "sk_draft": {"type": 'float', "default": 5.6, "min": 0.0, "max": 12.0, "step": 0.5, "group": 'Body', "label": 'Draft angle (deg)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.3537, p["sk_h"] * 0.0209).spline([(p["sk_w"] * 0.3537, p["sk_h"] * 0.0209), (p["sk_w"] * 0.3377, p["sk_h"] * 0.2398), (p["sk_w"] * 0.2316, p["sk_h"] * 0.4318)]).lineTo(p["sk_w"] * -0.1087, p["sk_h"] * 0.4612).bezier([(p["sk_w"] * -0.1087, p["sk_h"] * 0.4612), (p["sk_w"] * -0.3354, p["sk_h"] * 0.3427), (p["sk_w"] * -0.4644, p["sk_h"] * 0.1217)]).lineTo(p["sk_w"] * -0.1606, p["sk_h"] * -0.4269).bezier([(p["sk_w"] * -0.1606, p["sk_h"] * -0.4269), (p["sk_w"] * 0.036, p["sk_h"] * -0.4337), (p["sk_w"] * 0.2205, p["sk_h"] * -0.3653)]).spline([(p["sk_w"] * 0.2205, p["sk_h"] * -0.3653), (p["sk_w"] * 0.3282, p["sk_h"] * -0.1863), (p["sk_w"] * 0.3537, p["sk_h"] * 0.0209)]).close().extrude(p["sk_t"], taper=p["sk_draft"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
