import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003772 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_r": {"type": 'float', "default": 20, "min": 10.0, "max": 36.0, "step": 1.0, "group": 'Sketch', "label": 'Max radius (mm)'},
    "sk_h": {"type": 'float', "default": 55, "min": 27.5, "max": 99.0, "step": 1.0, "group": 'Sketch', "label": 'Height (mm)'},
}


def build(p):

    result = (cq.Workplane('XZ').moveTo(p["sk_r"] * 0.6406, p["sk_h"] * 0.0).bezier([(p["sk_r"] * 0.6406, p["sk_h"] * 0.0), (p["sk_r"] * 0.542, p["sk_h"] * 0.1037), (p["sk_r"] * 0.621, p["sk_h"] * 0.2073)]).bezier([(p["sk_r"] * 0.621, p["sk_h"] * 0.2073), (p["sk_r"] * 0.6332, p["sk_h"] * 0.3417), (p["sk_r"] * 0.5257, p["sk_h"] * 0.4761)]).lineTo(p["sk_r"] * 0.1839, p["sk_h"] * 0.5272).lineTo(p["sk_r"] * 0.2342, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.1014, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.1014, p["sk_h"] * 0.0).close().revolve())
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
