import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004687 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_r": {"type": 'float', "default": 27.43, "min": 13.7, "max": 49.4, "step": 1.0, "group": 'Sketch', "label": 'Max radius (mm)'},
    "sk_h": {"type": 'float', "default": 26.45, "min": 13.2, "max": 47.6, "step": 1.0, "group": 'Sketch', "label": 'Height (mm)'},
}


def build(p):

    result = (cq.Workplane('XZ').moveTo(p["sk_r"] * 0.3264, p["sk_h"] * 0.0).threePointArc((p["sk_r"] * 0.5126, p["sk_h"] * 0.2528), (p["sk_r"] * 0.568, p["sk_h"] * 0.5056)).lineTo(p["sk_r"] * 0.9448, p["sk_h"] * 0.6539).threePointArc((p["sk_r"] * 0.957, p["sk_h"] * 0.7626), (p["sk_r"] * 0.8902, p["sk_h"] * 0.8714)).lineTo(p["sk_r"] * 0.2704, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.118, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.118, p["sk_h"] * 0.0).close().revolve())
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
