import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004138 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 81.66, "min": 40.8, "max": 147.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 65, "min": 32.5, "max": 117.0, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 10, "min": 4.0, "max": 22.0, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "sk_hole_d": {"type": 'float', "default": 5.3, "min": 2.0, "max": 10.6, "step": 0.5, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "boss_d": {"type": 'float', "default": 24.1, "min": 12.1, "max": 48.2, "step": 1.0, "group": 'Boss', "label": 'Boss diameter (mm)'},
    "boss_h": {"type": 'float', "default": 9.4, "min": 3.8, "max": 23.5, "step": 1.0, "group": 'Boss', "label": 'Boss height (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.3068, p["sk_h"] * 0.1258).threePointArc((p["sk_w"] * 0.2018, p["sk_h"] * 0.3098), (p["sk_w"] * 0.0504, p["sk_h"] * 0.4125)).lineTo(p["sk_w"] * -0.3091, p["sk_h"] * -0.0995).threePointArc((p["sk_w"] * -0.1416, p["sk_h"] * -0.291), (p["sk_w"] * 0.0879, p["sk_h"] * -0.374)).threePointArc((p["sk_w"] * 0.2479, p["sk_h"] * -0.1676), (p["sk_w"] * 0.3068, p["sk_h"] * 0.1258)).close().extrude(p["sk_t"]))
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["sk_hole_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .circle(p["boss_d"] / 2).extrude(p["boss_h"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
