import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004084 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 75.28, "min": 37.6, "max": 135.5, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 61.54, "min": 30.8, "max": 110.8, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 6.0, "min": 2.4, "max": 13.2, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "sk_hole_d": {"type": 'float', "default": 6.4, "min": 2.0, "max": 12.8, "step": 0.5, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.379, p["sk_h"] * 0.0245).spline([(p["sk_w"] * 0.379, p["sk_h"] * 0.0245), (p["sk_w"] * 0.3005, p["sk_h"] * 0.2915), (p["sk_w"] * 0.089, p["sk_h"] * 0.4725)]).spline([(p["sk_w"] * 0.089, p["sk_h"] * 0.4725), (p["sk_w"] * -0.0346, p["sk_h"] * 0.4131), (p["sk_w"] * -0.1181, p["sk_h"] * 0.3043)]).threePointArc((p["sk_w"] * -0.3364, p["sk_h"] * 0.1547), (p["sk_w"] * -0.4324, p["sk_h"] * -0.0524)).lineTo(p["sk_w"] * -0.317, p["sk_h"] * -0.2746).threePointArc((p["sk_w"] * -0.0715, p["sk_h"] * -0.3731), (p["sk_w"] * 0.1813, p["sk_h"] * -0.3917)).lineTo(p["sk_w"] * 0.379, p["sk_h"] * 0.0245).close().extrude(p["sk_t"]))
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["sk_hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
