import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003858 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_r": {"type": 'float', "default": 30.09, "min": 15.0, "max": 54.2, "step": 1.0, "group": 'Sketch', "label": 'Max radius (mm)'},
    "sk_h": {"type": 'float', "default": 55, "min": 27.5, "max": 99.0, "step": 1.0, "group": 'Sketch', "label": 'Height (mm)'},
}


def build(p):

    result = (cq.Workplane('XZ').moveTo(p["sk_r"] * 0.2053, p["sk_h"] * 0.0).threePointArc((p["sk_r"] * 0.4747, p["sk_h"] * 0.1137), (p["sk_r"] * 0.8208, p["sk_h"] * 0.2274)).spline([(p["sk_r"] * 0.8208, p["sk_h"] * 0.2274), (p["sk_r"] * 0.6678, p["sk_h"] * 0.336), (p["sk_r"] * 0.626, p["sk_h"] * 0.4446)]).lineTo(p["sk_r"] * 0.7039, p["sk_h"] * 0.5894).lineTo(p["sk_r"] * 0.7789, p["sk_h"] * 0.8062).bezier([(p["sk_r"] * 0.7789, p["sk_h"] * 0.8062), (p["sk_r"] * 0.5955, p["sk_h"] * 0.8667), (p["sk_r"] * 0.2066, p["sk_h"] * 0.9273)]).threePointArc((p["sk_r"] * 0.4088, p["sk_h"] * 0.9637), (p["sk_r"] * 0.8173, p["sk_h"] * 1.0)).lineTo(p["sk_r"] * 0.0901, p["sk_h"] * 1.0).lineTo(p["sk_r"] * 0.0901, p["sk_h"] * 0.0).close().revolve())
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
