import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003878 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 82.93, "min": 41.5, "max": 149.3, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 89.86, "min": 44.9, "max": 161.7, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 6.43, "min": 2.6, "max": 14.1, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "sk_hole_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 8.6, "step": 0.5, "group": 'Holes', "label": 'Hole diameter (mm)'},
    "boss_d": {"type": 'float', "default": 16.6, "min": 8.3, "max": 33.2, "step": 1.0, "group": 'Boss', "label": 'Boss diameter (mm)'},
    "boss_h": {"type": 'float', "default": 8.4, "min": 3.4, "max": 21.0, "step": 1.0, "group": 'Boss', "label": 'Boss height (mm)'},
    "boss_bore_d": {"type": 'float', "default": 4.3, "min": 2.0, "max": 11.6, "step": 0.1, "group": 'Boss', "label": 'Bore diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.4413, p["sk_h"] * 0.1541).bezier([(p["sk_w"] * 0.4413, p["sk_h"] * 0.1541), (p["sk_w"] * 0.287, p["sk_h"] * 0.2879), (p["sk_w"] * 0.0898, p["sk_h"] * 0.3404)]).threePointArc((p["sk_w"] * -0.0627, p["sk_h"] * 0.3924), (p["sk_w"] * -0.1973, p["sk_h"] * 0.3647)).threePointArc((p["sk_w"] * -0.2979, p["sk_h"] * 0.2369), (p["sk_w"] * -0.3159, p["sk_h"] * 0.0571)).lineTo(p["sk_w"] * -0.209, p["sk_h"] * -0.3443).lineTo(p["sk_w"] * 0.2886, p["sk_h"] * -0.3379).lineTo(p["sk_w"] * 0.4413, p["sk_h"] * 0.1541).close().extrude(p["sk_t"]))
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["sk_hole_d"])
    )
    result = (
        result.faces('>Z').workplane()
        .circle(p["boss_d"] / 2).extrude(p["boss_h"])
    )
    result = (
        result.faces('>Z').workplane()
        .hole(p["boss_bore_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
