import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004405 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 63.74, "min": 31.9, "max": 114.7, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 47.13, "min": 23.6, "max": 84.8, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 30.0, "min": 12.0, "max": 66.0, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "sk_hole_d": {"type": 'float', "default": 8.4, "min": 2.0, "max": 16.8, "step": 0.5, "group": 'Holes', "label": 'Hole diameter (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.4456, p["sk_h"] * -0.0446).spline([(p["sk_w"] * 0.4456, p["sk_h"] * -0.0446), (p["sk_w"] * 0.3163, p["sk_h"] * 0.2036), (p["sk_w"] * 0.0899, p["sk_h"] * 0.3682)]).bezier([(p["sk_w"] * 0.0899, p["sk_h"] * 0.3682), (p["sk_w"] * -0.0159, p["sk_h"] * 0.3573), (p["sk_w"] * -0.1162, p["sk_h"] * 0.3219)]).lineTo(p["sk_w"] * -0.3603, p["sk_h"] * -0.097).lineTo(p["sk_w"] * -0.296, p["sk_h"] * -0.3308).threePointArc((p["sk_w"] * -0.0385, p["sk_h"] * -0.3905), (p["sk_w"] * 0.2258, p["sk_h"] * -0.3828)).lineTo(p["sk_w"] * 0.4456, p["sk_h"] * -0.0446).close().extrude(p["sk_t"]))
    result = (
        result.faces('>Z').workplane()
        .rarray(10.0, 10.0, 1, 1)
        .hole(p["sk_hole_d"])
    )
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
