import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004518 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "sk_w": {"type": 'float', "default": 86.51, "min": 43.3, "max": 155.7, "step": 1.0, "group": 'Sketch', "label": 'Sketch width (mm)'},
    "sk_h": {"type": 'float', "default": 54.06, "min": 27.0, "max": 97.3, "step": 1.0, "group": 'Sketch', "label": 'Sketch height (mm)'},
    "sk_t": {"type": 'float', "default": 25.51, "min": 10.2, "max": 56.1, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
}


def build(p):

    result = (cq.Workplane('XY').moveTo(p["sk_w"] * 0.4485, p["sk_h"] * -0.2107).threePointArc((p["sk_w"] * 0.21, p["sk_h"] * 0.152), (p["sk_w"] * -0.2366, p["sk_h"] * 0.3935)).lineTo(p["sk_w"] * -0.2956, p["sk_h"] * 0.1606).lineTo(p["sk_w"] * -0.0831, p["sk_h"] * -0.3217).spline([(p["sk_w"] * -0.0831, p["sk_h"] * -0.3217), (p["sk_w"] * 0.195, p["sk_h"] * -0.325), (p["sk_w"] * 0.4485, p["sk_h"] * -0.2107)]).close().extrude(p["sk_t"]))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
