import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004231 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 80.0, "min": 40.0, "max": 144.0, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 85, "min": 42.5, "max": 153.0, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_d": {"type": 'float', "default": 10.0, "min": 5.0, "max": 18.0, "step": 1.0, "group": 'Section', "label": 'Section diameter (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.0647, p["path_h"] * 0.4667), (p["path_w"] * 0.0, p["path_h"] * 0.8592), (p["path_w"] * 0.3005, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').circle(p["sweep_d"] / 2).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
