import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234003881 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 45, "min": 22.5, "max": 81.0, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 42.57, "min": 21.3, "max": 76.6, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_a": {"type": 'float', "default": 9.3, "min": 4.7, "max": 16.7, "step": 1.0, "group": 'Section', "label": 'Section width (mm)'},
    "sweep_b": {"type": 'float', "default": 6.9, "min": 3.5, "max": 12.4, "step": 1.0, "group": 'Section', "label": 'Section depth (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.0, p["path_h"] * 0.2431), (p["path_w"] * 0.2555, p["path_h"] * 0.4932), (p["path_w"] * 0.3463, p["path_h"] * 0.4985), (p["path_w"] * 0.3738, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').rect(p["sweep_a"], p["sweep_b"]).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
