import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004321 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 41.56, "min": 20.8, "max": 74.8, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 80, "min": 40.0, "max": 144.0, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_a": {"type": 'float', "default": 8.4, "min": 4.2, "max": 15.1, "step": 1.0, "group": 'Section', "label": 'Section width (mm)'},
    "sweep_b": {"type": 'float', "default": 5.3, "min": 2.6, "max": 9.5, "step": 1.0, "group": 'Section', "label": 'Section depth (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.4368, p["path_h"] * 0.4651), (p["path_w"] * 0.7869, p["path_h"] * 0.6665), (p["path_w"] * 0.7585, p["path_h"] * 0.8558), (p["path_w"] * 0.5359, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').rect(p["sweep_a"], p["sweep_b"]).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
