import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004481 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 61.27, "min": 30.6, "max": 110.3, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 110.0, "min": 55.0, "max": 198.0, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_a": {"type": 'float', "default": 20.7, "min": 10.3, "max": 37.3, "step": 1.0, "group": 'Section', "label": 'Section width (mm)'},
    "sweep_b": {"type": 'float', "default": 17.2, "min": 8.6, "max": 31.0, "step": 1.0, "group": 'Section', "label": 'Section depth (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.0, p["path_h"] * 0.5123), (p["path_w"] * 0.1801, p["path_h"] * 0.7571), (p["path_w"] * 0.0, p["path_h"] * 0.8077), (p["path_w"] * 0.0, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').rect(p["sweep_a"], p["sweep_b"]).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
