import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004646 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 70, "min": 35.0, "max": 126.0, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 65.55, "min": 32.8, "max": 118.0, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_a": {"type": 'float', "default": 21.3, "min": 10.7, "max": 38.3, "step": 1.0, "group": 'Section', "label": 'Section width (mm)'},
    "sweep_b": {"type": 'float', "default": 16.6, "min": 8.3, "max": 29.9, "step": 1.0, "group": 'Section', "label": 'Section depth (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.0, p["path_h"] * 0.2401), (p["path_w"] * 0.0588, p["path_h"] * 0.7438), (p["path_w"] * 0.1687, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').rect(p["sweep_a"], p["sweep_b"]).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
