import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004579 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 70, "min": 35.0, "max": 126.0, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 75, "min": 37.5, "max": 135.0, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_d": {"type": 'float', "default": 9.8, "min": 4.9, "max": 17.6, "step": 1.0, "group": 'Section', "label": 'Section diameter (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.3355, p["path_h"] * 0.2067), (p["path_w"] * 0.2212, p["path_h"] * 0.5204), (p["path_w"] * 0.4171, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').circle(p["sweep_d"] / 2).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
