import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004489 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 80.0, "min": 40.0, "max": 144.0, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 105, "min": 52.5, "max": 189.0, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_d": {"type": 'float', "default": 8.4, "min": 4.2, "max": 15.1, "step": 1.0, "group": 'Section', "label": 'Section diameter (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.4442, p["path_h"] * 0.4569), (p["path_w"] * 0.7286, p["path_h"] * 0.6818), (p["path_w"] * 0.914, p["path_h"] * 0.7835), (p["path_w"] * 1.0, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').circle(p["sweep_d"] / 2).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
