import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004098 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 40, "min": 20.0, "max": 72.0, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 100, "min": 50.0, "max": 180.0, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_a": {"type": 'float', "default": 17.7, "min": 8.8, "max": 31.9, "step": 1.0, "group": 'Section', "label": 'Section width (mm)'},
    "sweep_b": {"type": 'float', "default": 15.8, "min": 7.9, "max": 28.4, "step": 1.0, "group": 'Section', "label": 'Section depth (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.0, p["path_h"] * 0.3976), (p["path_w"] * 0.0, p["path_h"] * 0.655), (p["path_w"] * 0.0, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').rect(p["sweep_a"], p["sweep_b"]).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
