import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004435 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 65.74, "min": 32.9, "max": 118.3, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 50.49, "min": 25.2, "max": 90.9, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_d": {"type": 'float', "default": 8.0, "min": 4.0, "max": 14.4, "step": 1.0, "group": 'Section', "label": 'Section diameter (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.0, p["path_h"] * 0.6821), (p["path_w"] * 0.2657, p["path_h"] * 0.7269), (p["path_w"] * 0.5866, p["path_h"] * 0.766), (p["path_w"] * 0.631, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').circle(p["sweep_d"] / 2).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
