import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004023 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 41.85, "min": 20.9, "max": 75.3, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 60, "min": 30.0, "max": 108.0, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_a": {"type": 'float', "default": 12.7, "min": 6.3, "max": 22.9, "step": 1.0, "group": 'Section', "label": 'Section width (mm)'},
    "sweep_b": {"type": 'float', "default": 7.5, "min": 3.8, "max": 13.5, "step": 1.0, "group": 'Section', "label": 'Section depth (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.1744, p["path_h"] * 0.5603), (p["path_w"] * 0.1118, p["path_h"] * 0.8803), (p["path_w"] * 0.2665, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').rect(p["sweep_a"], p["sweep_b"]).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
