import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004630 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 56.36, "min": 28.2, "max": 101.4, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 51.54, "min": 25.8, "max": 92.8, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_d": {"type": 'float', "default": 16.8, "min": 8.4, "max": 30.2, "step": 1.0, "group": 'Section', "label": 'Section diameter (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.0, p["path_h"] * 0.5583), (p["path_w"] * 0.373, p["path_h"] * 0.719), (p["path_w"] * 0.4619, p["path_h"] * 0.8312), (p["path_w"] * 0.3424, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').circle(p["sweep_d"] / 2).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
