import cadquery as cq

# Generated by CadQuarry v0.6.0 — seed 1234004008 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "path_w": {"type": 'float', "default": 58.07, "min": 29.0, "max": 104.5, "step": 1.0, "group": 'Path', "label": 'Path width (mm)'},
    "path_h": {"type": 'float', "default": 105, "min": 52.5, "max": 189.0, "step": 1.0, "group": 'Path', "label": 'Path length (mm)'},
    "sweep_a": {"type": 'float', "default": 14.7, "min": 7.3, "max": 26.5, "step": 1.0, "group": 'Section', "label": 'Section width (mm)'},
    "sweep_b": {"type": 'float', "default": 10.9, "min": 5.5, "max": 19.6, "step": 1.0, "group": 'Section', "label": 'Section depth (mm)'},
}


def build(p):

    _path = cq.Workplane('XZ').spline([(p["path_w"] * 0.0, p["path_h"] * 0.0), (p["path_w"] * 0.3057, p["path_h"] * 0.776), (p["path_w"] * 0.2142, p["path_h"] * 0.8369), (p["path_w"] * 0.0958, p["path_h"] * 1.0)])
    result = (cq.Workplane('XY').rect(p["sweep_a"], p["sweep_b"]).sweep(_path))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
