import cadquery as cq
from bd_warehouse import thread as _bdt
import build123d as _bd

# Generated by CadQuarry v0.6.0 — seed 1234004124 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "major_d": {"type": 'float', "default": 5.0, "min": 3.0, "max": 24.0, "step": 0.5, "group": 'Thread', "label": 'Thread major Ø (mm)'},
    "pitch": {"type": 'float', "default": 0.8, "min": 0.35, "max": 3.5, "step": 0.05, "group": 'Thread', "label": 'Thread pitch (mm)'},
    "height": {"type": 'float', "default": 10.8, "min": 6.0, "max": 19.4, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "plate_w": {"type": 'float', "default": 80, "min": 48.0, "max": 128.0, "step": 1.0, "group": 'Body', "label": 'Plate width (mm)'},
    "plate_d": {"type": 'float', "default": 76.8, "min": 46.1, "max": 122.9, "step": 1.0, "group": 'Body', "label": 'Plate depth (mm)'},
}


def build(p):

    _W, _D, _H = p["plate_w"], p["plate_d"], p["height"]
    _major, _pitch = p["major_d"], p["pitch"]
    _body = _bd.Box(_W, _D, _H)
    _sx, _sy = p["plate_w"] * 0.6, p["plate_d"] * 0.6
    _locs = [(_xx, _yy) for _xx in (-_sx / 2, _sx / 2) for _yy in (-_sy / 2, _sy / 2)]
    for _x, _y in _locs:
        _body = _body - (_bd.Pos(_x, _y, 0) * _bd.Cylinder(radius=_major / 2, height=_H))
        _thr = _bdt.IsoThread(major_diameter=_major, pitch=_pitch, length=_H, external=False, end_finishes=('fade', 'fade'))
        _body = _body + (_bd.Location((_x, _y, -_H / 2)) * _thr)
    result = cq.Workplane('XY').add(cq.Solid(_body.wrapped))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
