import cadquery as cq
from bd_warehouse import thread as _bdt
import build123d as _bd

# Generated by CadQuarry v0.6.0 — seed 1234004724 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "major_d": {"type": 'float', "default": 16.0, "min": 3.0, "max": 24.0, "step": 0.5, "group": 'Thread', "label": 'Thread major Ø (mm)'},
    "pitch": {"type": 'float', "default": 2.0, "min": 0.35, "max": 3.5, "step": 0.05, "group": 'Thread', "label": 'Thread pitch (mm)'},
    "height": {"type": 'float', "default": 25.6, "min": 19.2, "max": 46.1, "step": 1.0, "group": 'Body', "label": 'Thickness (mm)'},
    "body_d": {"type": 'float', "default": 47.8, "min": 28.8, "max": 76.5, "step": 1.0, "group": 'Body', "label": 'Outer Ø (mm)'},
}


def build(p):

    _W = _D = p["body_d"]
    _H = p["height"]
    _major, _pitch = p["major_d"], p["pitch"]
    _body = _bd.Cylinder(radius=_W / 2, height=_H)
    _locs = [(0.0, 0.0)]
    for _x, _y in _locs:
        _body = _body - (_bd.Pos(_x, _y, 0) * _bd.Cylinder(radius=_major / 2, height=_H))
        _thr = _bdt.IsoThread(major_diameter=_major, pitch=_pitch, length=_H, external=False, end_finishes=('fade', 'fade'))
        _body = _body + (_bd.Location((_x, _y, -_H / 2)) * _thr)
    result = cq.Workplane('XY').add(cq.Solid(_body.wrapped))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
