import cadquery as cq
from bd_warehouse import thread as _bdt
import build123d as _bd

# Generated by CadQuarry v0.6.0 — seed 1234004162 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "major_d": {"type": 'float', "default": 8.0, "min": 4.0, "max": 24.0, "step": 0.5, "group": 'Thread', "label": 'Major diameter (mm)'},
    "pitch": {"type": 'float', "default": 1.25, "min": 0.62, "max": 2.5, "step": 0.05, "group": 'Thread', "label": 'Pitch (mm)'},
    "thread_len": {"type": 'float', "default": 35.6, "min": 14.2, "max": 71.2, "step": 1.0, "group": 'Thread', "label": 'Thread length (mm)'},
}


def build(p):

    _thr = _bdt.IsoThread(major_diameter=p["major_d"], pitch=p["pitch"], length=p["thread_len"], external=True, end_finishes=("fade", "fade"))
    _r = _thr.min_radius if hasattr(_thr, 'min_radius') else _thr.root_radius
    _shank = _bd.Cylinder(radius=_r, height=p["thread_len"], align=(_bd.Align.CENTER, _bd.Align.CENTER, _bd.Align.MIN))
    _part = _shank + _thr
    result = cq.Workplane('XY').add(cq.Solid(_part.wrapped))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
