import cadquery as cq
from bd_warehouse import thread as _bdt
import build123d as _bd

# Generated by CadQuarry v0.5.0 — seed 1234003770 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "thread_size": {"type": 'enum', "default": '18x4', "choices": ['8x1.5', '10x2', '12x3', '14x3', '16x4', '18x4', '20x4', '24x5', '28x5', '30x6', '36x6', '40x7'], "group": 'Thread', "label": 'Size designation'},
    "thread_len": {"type": 'float', "default": 51.5, "min": 20.6, "max": 103.0, "step": 1.0, "group": 'Thread', "label": 'Thread length (mm)'},
}


def build(p):

    _thr = _bdt.MetricTrapezoidalThread(size=p["thread_size"], length=p["thread_len"], external=True, end_finishes=("fade", "fade"))
    _r = _thr.min_radius if hasattr(_thr, 'min_radius') else _thr.root_radius
    _shank = _bd.Cylinder(radius=_r, height=p["thread_len"], align=(_bd.Align.CENTER, _bd.Align.CENTER, _bd.Align.MIN))
    _part = _shank + _thr
    result = cq.Workplane('XY').add(cq.Solid(_part.wrapped))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
