import cadquery as cq
from bd_warehouse import thread as _bdt
import build123d as _bd

# Generated by CadQuarry v0.6.0 — seed 1234003867 — CC0-1.0
# https://github.com/jacobjennings/CadQuarry

PARAMS = {
    "major_d": {"type": 'float', "default": 5.0, "min": 4.0, "max": 24.0, "step": 0.5, "group": 'Thread', "label": 'Major diameter (mm)'},
    "pitch": {"type": 'float', "default": 0.8, "min": 0.4, "max": 1.6, "step": 0.05, "group": 'Thread', "label": 'Pitch (mm)'},
    "thread_len": {"type": 'float', "default": 22.8, "min": 9.1, "max": 45.6, "step": 1.0, "group": 'Thread', "label": 'Thread length (mm)'},
}


def build(p):

    _thr = _bdt.IsoThread(major_diameter=p["major_d"], pitch=p["pitch"], length=p["thread_len"], external=False, end_finishes=("fade", "fade"))
    _body = _bd.Cylinder(radius=(p["major_d"]) * 0.9, height=p["thread_len"], align=(_bd.Align.CENTER, _bd.Align.CENTER, _bd.Align.MIN))
    _bore = _bd.Cylinder(radius=(p["major_d"]) / 2, height=p["thread_len"], align=(_bd.Align.CENTER, _bd.Align.CENTER, _bd.Align.MIN))
    _part = (_body - _bore) + _thr
    result = cq.Workplane('XY').add(cq.Solid(_part.wrapped))
    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
