import cadquery as cq

# Generated by CadQuarry v0.1.0 — seed 42 — CC0-1.0
# Example: flanged hub with bolt-circle holes.
PARAMS = {
    "outer_d":   {"type": "float", "default": 40.0, "min": 20.0, "max": 100.0, "step": 1.0, "group": "Body",   "label": "Hub diameter (mm)"},
    "inner_d":   {"type": "float", "default": 20.0, "min": 6.0,  "max": 60.0,  "step": 0.5, "group": "Body",   "label": "Bore diameter (mm)"},
    "length":    {"type": "float", "default": 30.0, "min": 10.0, "max": 80.0,  "step": 1.0, "group": "Body",   "label": "Hub length (mm)"},
    "flange_d":  {"type": "float", "default": 80.0, "min": 55.0, "max": 160.0, "step": 1.0, "group": "Flange", "label": "Flange diameter (mm)"},
    "flange_h":  {"type": "float", "default": 6.0,  "min": 2.0,  "max": 15.0,  "step": 0.5, "group": "Flange", "label": "Flange height (mm)"},
    "bolt_d":    {"type": "float", "default": 6.4,  "min": 3.2,  "max": 10.5,  "step": 0.1, "group": "Bolts",  "label": "Bolt hole diameter (mm)"},
    "bolt_r":    {"type": "float", "default": 32.0, "min": 22.0, "max": 52.0,  "step": 1.0, "group": "Bolts",  "label": "Bolt circle radius (mm)"},
    "n_bolts":   {"type": "int",   "default": 6,    "min": 3,    "max": 12,    "step": 1,   "group": "Bolts",  "label": "Number of bolts"},
    "chamfered": {"type": "bool",  "default": True,                                          "group": "Body",   "label": "End chamfers"},
}


def build(p):
    od = p["outer_d"] / 2
    id_ = p["inner_d"] / 2
    fd = p["flange_d"] / 2
    h = p["length"]
    fh = p["flange_h"]

    result = (
        cq.Workplane("XZ")
        .moveTo(id_, 0)
        .lineTo(fd, 0)
        .lineTo(fd, fh)
        .lineTo(od, fh)
        .lineTo(od, h)
        .lineTo(id_, h)
        .close()
        .revolve()
    )

    result = (
        result.faces(">Z").workplane()
        .polarArray(p["bolt_r"], 0, 360, p["n_bolts"])
        .hole(p["bolt_d"])
    )

    if p["chamfered"]:
        result = result.edges("<Z").chamfer(0.5)

    return result


result = build({k: v["default"] for k, v in PARAMS.items()})
